### ISSUE TITLE
No uri registered to handle redirect or multiple applications registered

### ISSUE THREAD

**Issue by albka1986** [okta/okta-oidc-android#100]
How to deal with the error:
**E/SyncWebAuthClientImpl:No uri registered to handle redirect or multiple applications registered**

I've set config:
```
config = OIDCConfig.Builder()
.clientId(“id here”)
.redirectUri(“https://domain.okta.com/login/callback”)
.endSessionRedirectUri(“https://domain.okta.com/login/callback”)
.scopes(“openid”, “profile”, “offline_access”)
.discoveryUri(“https://domain.okta.com”)
.create()
```
and

```
android.defaultConfig.manifestPlaceholders = [
“appAuthRedirectScheme”: “com.okta.domain”
]
```

Data was taken from there:
http://prntscr.com/p7nz29
I stuck with this, please help.

**Comment by FeiChen-okta** [comment]
In your org settings you can remove "https://" from the URIs
then setup config:

```bash
config = OIDCConfig.Builder()
.clientId(“id here”)
.redirectUri(“domain.okta.com/login/callback”)
.endSessionRedirectUri(“domain.okta.com/login/callback”)
.scopes(“openid”, “profile”, “offline_access”)
.discoveryUri(“https://domain.okta.com”)
.create()
```
and

```bash
android.defaultConfig.manifestPlaceholders = [
“appAuthRedirectScheme”: “domain.okta.com”
]
```

**Comment by albka1986** [comment]
Unfortunately, It doesn't help me. I get the same error:
**No uri registered to handle redirect or multiple applications registered**


My current config:
```
config = OIDCConfig.Builder()
            .clientId("0oa1b93ai3SmmP0me357")
            .redirectUri("domain.okta.com/login/callback")
            .endSessionRedirectUri("domain.okta.com/login/logout")
            .scopes("openid", "profile", "offline_access")
            .discoveryUri("https://domain.okta.com")
            .create()
```

and

```
 android.defaultConfig.manifestPlaceholders = [
                "appAuthRedirectScheme": "domain.okta.com"
        ]
```

**Comment by FeiChen-okta** [comment]
Heres a config of my sample:

![Screen Shot 2019-09-19 at 9 18 50 AM](https://user-images.githubusercontent.com/46411069/65262313-edd03f00-dabe-11e9-909a-3995ffeb0875.png)

```bash
config = OIDCConfig.Builder()
            .clientId("CLIENT_ID")
            .redirectUri("com.first.sample:/callback")
            .endSessionRedirectUri("com.first.sample:/logout")
            .scopes("openid", "profile", "offline_access")
            .discoveryUri("https://com.first.sample")
            .create()
```

```bash
 android.defaultConfig.manifestPlaceholders = [
                "appAuthRedirectScheme": "com.first.sample"
        ]
```

Since you have the scope `offline_access` make sure you have Refresh token checked.

Also check that you don't have multiple apps with the same redirect scheme:
```bash
#adb shell dumpsys package | grep com.first.sample
adb shell dumpsys package | grep manifestScheme
```

**Comment by albka1986** [comment]
Where can I find "appAuthRedirectScheme"?

**Comment by albka1986** [comment]
I had removed the "https://" from my code and from OKTA Admin Panel and it helped me. Thanks!

**Comment by yahmi** [comment]
hello , 
I followed all steps and still have the same problem  could you tell me please where is the problem  @albka1986 @JayNewstrom 

{
  "client_id": "0oa1fsebdxO8R63eu5d7",
  "redirect_uri": "com.okta.dev-00357442:/callback",
  "end_session_redirect_uri": "com.okta.dev-00357442:/logout",
  "scopes": [
    "openid",
    "profile",
    "offline_access"
  ],
  "discovery_uri": "dev-00357442.okta.com"
}

**Comment by NikitaAvraimov-okta** [comment]
@yahmi can you make sure you have added redirect scheme to build.gradle and have no apps currently installed with same redirect sheme, please

**Comment by yahmi** [comment]
@NikitaAvraimov-okta  yes i did all these steps

**Comment by yahmi** [comment]
@NikitaAvraimov-okta @JayNewstrom 
hello , 
Even the simple for web sign on , i put the configuration get the same error

**Comment by JayNewstrom** [comment]
@yahmi could you look at the comment from this similar issue: https://github.com/okta/okta-oidc-android/issues/233#issuecomment-828143005

If you can provide more information, I'd be happy to help.

**Comment by yahmi** [comment]
@JayNewstrom  fixed with @NikitaAvraimov-okta   thanks a lot

**Comment by MeghaR2408** [comment]
Hi, I'm also getting the same error, please review my configuration & let me know, what am I doing wrong here:

Build Gradle
`manifestPlaceholders = [
                "webAuthenticationRedirectScheme": parseScheme(oktaProperties.getProperty('signInRedirectUri')),
                "appAuthRedirectScheme": "com.okta.dev-44517624"
        ]`

Configuration File

`package sample.okta.android

internal object Configuration {
    const val SIGN_IN_REDIRECT_URI: String = "com.okta.dev-44517624:/callback"
    const val SIGN_OUT_REDIRECT_URI: String = "com.okta.dev-44517624:/callback"
    const val CLIENT_ID: String = "0oa6s2vycxfdOvMuQ5d7"
    const val ISSUER: String = "https://dev-44517624.okta.com/oauth2/default"
    const val DEFAULT_SCOPE: String = "openid email profile offline_access device_sso"
    const val DISCOVERY_URI: String = "https://com.okta.dev-44517624"
}`

 
Build Method

`var oidcConfig = OIDCConfig.Builder()
                .clientId(Configuration.CLIENT_ID)
                .redirectUri(Configuration.SIGN_IN_REDIRECT_URI)
                .endSessionRedirectUri(Configuration.SIGN_OUT_REDIRECT_URI)
                .scopes("openid", "profile", "offline_access", "email", "device_sso")
                .discoveryUri(Configuration.DISCOVERY_URI)
                .create()`
