### ISSUE TITLE
Cannot load json configuration file

### ISSUE THREAD

**Issue by gtupak** [okta/okta-oidc-android#121]
This might sound like a stupid question as I'm fairly new to Android, but when trying to load the json file like in the example

```
OIDCConfig config = new OIDCConfig.Builder()
    .withJsonFile(this, R.id.okta_oidc_config)
    .create();
```

I get an `Unresolved reference: okta_oidc_config`. I put the json file in res/raw with the name `okta_oidc_config.json` like described.

Also, I see the file is referenced as `R.id.okta_oidc_config` in the  [Using JSON configuration file section](https://github.com/okta/okta-oidc-android#using-json-configuration-file) but `R.raw.okta_oidc_config` in the [onActivityResult override section](https://github.com/okta/okta-oidc-android#onactivityresult-override).

Am I missing anything? Thanks in advance!

**Comment by FeiChen-okta** [comment]
@gtupak It should be 

```java
OIDCConfig config = new OIDCConfig.Builder()
    .withJsonFile(this, R.raw.okta_oidc_config)
    .create();
```

**Comment by gtupak** [comment]
I tried it with `R.raw` as well and it still didn’t recognize the file. Gave me the same error (unresolved reference)

**Comment by FeiChen-okta** [comment]
Android generates the R.java automatically. If it can't find the res/raw file in your folder then you probably did not import the correct R class. Check your imports to see if you have a different R class than the one for your apps package. You can also directly specific it by

```java
//{packagename}.R.raw.okta_oidc_config
com.okta.sample.R.raw.okta_oidc_config
```

**Comment by gtupak** [comment]
Hey, my file contained `import android.R`. After I removed it, `R.raw.okta_oidc_config` was instantly recognized, thanks for your help! :)
