### ISSUE TITLE
Library doesn't works with AndroidX

### ISSUE THREAD

**Issue by sadiqueshannure** [okta/okta-oidc-android#123]
As this library uses com.android.support, this library is not working with any project which uses AndroidX.

Any plan update support for AndroidX.

**Comment by FeiChen-okta** [comment]
Hi @sadiqueshannure Where do you see com.android.support being used?
This library only using androidx libraries. This is from the gradle file:

```gradle
    implementation "androidx.browser:browser:${rootProject.browserVersion}"
    implementation "androidx.fragment:fragment:${rootProject.androidxLibVersion}"
    implementation "androidx.core:core:${rootProject.androidxLibVersion}"
```

**Comment by alexzaitsev** [comment]
Perfectly works with AndroidX, seems this issue is outdated.
