### ISSUE TITLE
AuthorizationException: Lib refuses to access /userinfo endpoint despite server supporting OpenID

### ISSUE THREAD

**Issue by yM1ndst0rM** [okta/okta-oidc-android#127]
We have implemented okta integration for a native Android and iOS app. While the integration works fine on iOS the Android library refuses to query data from the `/userinfo` endpoint because the discovery URI contains `oauth2`. This is the exception that is being generated:

https://github.com/okta/okta-oidc-android/blob/7995eff60cb7df31d358d6e609977a2f1b1debd3/library/src/main/java/com/okta/oidc/clients/sessions/SyncSessionClientImpl.java#L105

**Questions**

1. Is this a misconfiguration of our authentication server? We have not found a way of changing the discovery URI to not include `[...]/oauth2/[...]`. The documentation seems to suggest that it is to be expected (See here https://developer.okta.com/docs/reference/api/oidc/#composing-your-base-url). Also the iOS lib works fine as is so a server misconfiguration seems unlikely.

2. Is this a misconfiguration of the Android library? Currently the discovery URI in the config JSON looks like this: `"discovery_uri": "https://[...]/oauth2/default"` Any other configuration does not allow the app to authenticate to that specific auth server.

3. If this is unintended library behavior is there a workaround for us to use the `/userinfo` endpoint? (Save from quering the hardcoded endpoint ourselves and potentially experiencing problems further down the road.)

Thank you for your time, cheers!

PS.: Additional info

Version of Android lib: `com.okta.android:oidc-androidx:1.0.6`
Project minSdk: 21
Project targetSdk: 28

Error is produced by the call to 
https://github.com/okta/okta-oidc-android/blob/7995eff60cb7df31d358d6e609977a2f1b1debd3/library/src/main/java/com/okta/oidc/clients/sessions/SessionClient.java#L127

**Comment by FeiChen-okta** [comment]
Hi @yM1ndst0rM The uri you used `https://{yourOktaDomain}/oauth2/default` will append .`well-known/oauth-authorization-server` by default. That server configuration does not provide /userinfo endpoint as that is only available on a OIDC configuration. So to fix this you can use the full uri:
`https://{yourOktaDomain}/oauth2/default/.well-known/openid-configuration`
Or use `https://{yourOktaDomain}`

For more information on configuring the discoveryUri:
https://github.com/okta/okta-oidc-android/#Configuration

**Comment by yM1ndst0rM** [comment]
Hi @FeiChen-okta thank you for your quick reply!
This fully qualified uri `https://{yourOktaDomain}/oauth2/default/.well-known/openid-configuration` solved my issue! Great!

Further insights I that might be helpful:
- Replacing the discovery URL with https://{yourOktaDomain} works for getting the `/userinfo` endpoint but is also seemingly talking to a different authentication server since the tokens recieved there cannot be used by our systems.
- When the discovery URL is changed during development without completely wiping the application from the device the library just never returns from the refreshTokens call. This is not a big deal in production but it cost me some time in development and is definitely not an outcome I would have expected.

Closing this issue as it is solved. If you like I can open separate issues for the insights.
Cheers!

**Comment by FeiChen-okta** [comment]
Hi @yM1ndst0rM Thanks for the feedback
- Yes if using `https://{yourOktaDomain}` it will use the default OIDC server. you can use something like `https://{yourOktaDomain}/oauth2/{serverId}/.well-known/openid-configuration` if you have your own server ID.
- Regarding the refresh token, this should be handled by the SDK. I'll add an internal task to fix.

**Comment by alexzaitsev** [comment]
Faced with the same issue. Solution is to point a full discovery URI with `.well-known/openid-configuration` ending. Don't forget to re-install the app if discovery URI wasn't changed just after restart.

**Comment by jdnichollsc** [comment]
Hello guys,

We're getting the following error from Android:
```
{"error_message":null,"error_code":"-600"}
```
We're using that configuration with the @okta/okta-react-native package, from iOS it works perfect.
Our **discoveryUri** is: `https://{yourOktaDomain}/oauth2/${authServerId}`

**Comment by FeiChen-okta** [comment]
Hi @jdnichollsc,

Does this happen on `createConfig`? Which part of the flow does the error come from? If it is from `createConfig` then the issue is not the discoveryUri since it is not being used at that point. When creating a config, the Android part validates the following are not null or empty:
clientId, redirectUri, endSessionRedirectUri, discoveryUri, scopes

**Comment by jdnichollsc** [comment]
We're calling the `createConfig` before to authenticate and get the access token, in the meantime it's working with a little bit hacky validation:
```
discoveryUri: config.OKTA_ISSUER_URL + (
  Platform.OS === 'android' ? '/.well-known/openid-configuration' : ''
)
```
We're using a code similar to this: https://github.com/okta/samples-js-react-native/blob/master/custom-sign-in/app/ProfileScreen.js#L58
