### ISSUE TITLE
Redirect/Logout URIs starts from http://

### ISSUE THREAD

**Issue by alexzaitsev** [okta/okta-oidc-android#131]
Hello @FeiChen-okta 
Is it possible to use redirect/logout URIs starting from "http://"? 
I'm integrating with corporate okta server that supports URIs that starts only from "http://" or "https://".
Thanks for any information.

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev you can try using android [app links](https://developer.android.com/training/app-links) but I don't see a reason to do that. The redirect URI scheme doesn't need to start with `https://`. The redirect URI is only for redirecting to the native from chrome custom tabs. It is not redirecting to a web page, so even if Okta servers require `https`, this doesn't apply to native applications.

**Comment by alexzaitsev** [comment]
Thank you for the information. I've contacted with the support of my okta server and they added redirect/logout URI with custom scheme manually. Now that works. Thanks.
