### ISSUE TITLE
"Invalid discovery document" on release apk

### ISSUE THREAD

**Issue by baloi91** [okta/okta-oidc-android#132]
Everything works fine in debug mode, but when I manage to export release apk app then it says:
AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid discovery document"}.

My config json:
`{
  "client_id": "0oa1v98k9zfVDU2XXXX",
  "redirect_uri": "com.okta.dev-999999:/callback",
  "end_session_redirect_uri": "com.okta.dev-999999:/logout",
  "scopes": [
    "openid",
    "profile",
    "offline_access"
  ],
  "discovery_uri": "https://login.example.com/oauth2/default"
}`

Thanks

**Comment by FeiChen-okta** [comment]
Hi @baloi91 the URI `https://login.example.com/oauth2/default` is an invalid address. I tried it on my browser and postman so it is not a valid configuration. This should not work in debug also. 
Do you mean your android application works in debug mode or the Okta server configuration is in preview?

**Comment by FeiChen-okta** [comment]
Hi @baloi91. I checked the url and it should work. I tried with`https://login.ceterus.com/oauth2/default/.well-known/openid-configuration` and
`https://login.ceterus.com/oauth2/default/.well-known/oauth-authorization-server`
Both of them should work since the json returned from postman is what the SDK expects. It is odd that it works in debug build but doesn't in release. It sounds like a build issue where it is not picking up the json file. You can try using the `OIDCConfig.Builder` to set it programatically. Do you have the stacktrace of the exception?

**Comment by baloi91** [comment]
I thought of json issue too, so I switch to set it in code
`        OIDCConfig config = new OIDCConfig.Builder()
                .clientId("0oa1v98k9zfVDU2PXXXX")
                .redirectUri("com.okta.dev-999999:/callback")
                .endSessionRedirectUri("com.okta.dev-999999:/logout")
                .scopes("openid", "profile", "offline_access")
                .discoveryUri("https://login.ceterus.com/oauth2/default/.well-known/oauth-authorization-server")
                .create();`
but it doesn't work.

The following log printed out when I call signIn fuction:
`12-19 10:37:58.951 26785-26785/com.ceterusinc.edge D/ViewRootImpl: ViewPostImeInputStage processPointer 0
12-19 10:37:59.061 26785-26785/com.ceterusinc.edge D/ViewRootImpl: ViewPostImeInputStage processPointer 1
12-19 10:37:59.061 26785-6502/com.ceterusinc.edge I/System.out: (HTTPLog)-Static: Hongbao
12-19 10:37:59.061 26785-6502/com.ceterusinc.edge I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-19 10:37:59.061 26785-6502/com.ceterusinc.edge I/System.out: (HTTPLog)-Static: Hongbao
12-19 10:37:59.071 26785-6502/com.ceterusinc.edge I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-19 10:37:59.331 26785-26785/com.ceterusinc.edge I/error: Authorization error
12-19 10:37:59.331 26785-26785/com.ceterusinc.edge I/error2: AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid discovery document"}
`

**Comment by FeiChen-okta** [comment]
Could you catch that exception and print the stack trace? That will pinpoint where in the `ProviderConfiguration` that is causing this. Also try disabling proguard or R8 since it is working in debug and not release. It could be obfuscation issue.

**Comment by baloi91** [comment]
Thank you @FeiChen-okta , although disabling proguard is not help, but set minifyEnable to false seems to fix the issue. I'm not quite sure how it was fixed but release apk now work as expected. I'll research more about this, it is my first Android project :)) and I'll close this issue then. Thanks again for your support, that's very kind of you!

**Comment by ScottSusman** [comment]
I know this is closed but I encounter the exact same issue (down to "it worked in debug but not release" and "it worked on iOS but not Android").  Turned out Proguard was removing required files.  I added `-keep class com.okta.oidc.** { *; }` to my `proguard-rules.pro` and resolved the issue.
