### ISSUE TITLE
Discovery URI is not in the root

### ISSUE THREAD

**Issue by alexzaitsev** [okta/okta-oidc-android#133]
Is it possible to set discovery URI that is not like "https://example.com" but "https://example.com/any/another/url"?
Seems that now we always go to "https://example.com"

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev, Yes it is possible to set the discovery URI to your companies domain. This is dependent on how you configure the okta server. If your authentication server is at `https://{yourCompany}` you can add the following at the end `.well-known/openid-configuration`. For more information see the following:
https://github.com/okta/okta-oidc-android#Configuration

**Comment by alexzaitsev** [comment]
Your information is correct but my issue was in another thing: seems that library stores discovery URI in the storage and the developer needs to reinstall the app after its change.

**Comment by JayNewstrom** [comment]
Please reopen if this is not fixed.
