### ISSUE TITLE
Default Browser Only?

### ISSUE THREAD

**Issue by davidhartley** [okta/okta-oidc-android#136]
We are getting reports from some of our users that the login process via browser is only working if Chrome is set to their _default_ browser at the OS level, not if it is just installed. Is this expected? I don't see anything about default browser in the documentation.

**Comment by FeiChen-okta** [comment]
Hi @davidhartley I'm suspecting the installed browser is being filtered out by the OS.
This sounds similar to this issue:
https://github.com/okta/okta-oidc-android/issues/110

This is due to the OS filtering out that browser. A fix is to use a MATCH_ALL flag but we decided not to do it.

**Comment by davidhartley** [comment]
@FeiChen-okta would it be possible to add it this as an _option_ for clients to use? I understand not wanting to default to it, but it's a difficult think to communicate to users who use other browsers by default.

**Comment by FeiChen-okta** [comment]
@davidhartley yes it is possible to add as an option. We will discuss this internally.

**Comment by FeiChen-okta** [comment]
Added MATCH_ALL option in version 1.0.9
