### ISSUE TITLE
Android 9 Support & Performance

### ISSUE THREAD

**Issue by jdnichollsc** [okta/okta-oidc-android#137]
Hi guys,

We're testing this library from our app using @okta/okta-react-native package and we're having issues in Android 9, in some devices like Xiaomi Note 5. So we want to know if this library supports Android 9, because it works perfect testing from multiple devices with Android 10.

Thanks in advance!

**Comment by FeiChen-okta** [comment]
Hi @jdnichollsc This library supports Android 9. Are you having issues with the stand alone library or the react-native bridge?

**Comment by jdnichollsc** [comment]
I'm not sure if the issue is related with the react-native bridge, but we're gettings this performance issue only from Android, from iOS the react-native package works perfect

**Comment by FeiChen-okta** [comment]
@jdnichollsc what is the latest version of react native you are using? A month back the react-native had a change to use the latest version of the library 1.0.8. The latest version fixed an issue that can cause performance issues on devices with TEE such as the Pixel 3.

**Comment by jdnichollsc** [comment]
ohh ok, it looks like we're having performance issues by calling [createConfig](https://www.npmjs.com/package/@okta/okta-react-native#createconfig) multiple times, before to call okta functions, we're going to add a Singleton validation of that call, thanks!

**Comment by jdnichollsc** [comment]
Ohh ok guys, as we can indetify we're getting this error from some devices: https://github.com/okta/okta-oidc-android/issues/113
And that's related with the performance issues we're having in some Android devices

Any help is really appreciated! 👍

**Comment by FeiChen-okta** [comment]
Hi @jdnichollsc, The latest library is not using TEE so the performance issue is fixed. The application should clear the data if it encounters that key invalidated since it needs to generate new keys.

**Comment by jdnichollsc** [comment]
@FeiChen-okta do you know if that version of the library is used from the latest version of @okta/okta-react-native? thanks in advance!

**Comment by FeiChen-okta** [comment]
@jdnichollsc Yes it is using the latest 
https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react-native/android/build.gradle

**Comment by jdnichollsc** [comment]
>The application should clear the data if it encounters that key invalidated since it needs to generate new keys
Hi Fei, thanks for your quickly response! One question about this comment, how can I do that using the RN package? using [clearTokens](https://www.npmjs.com/package/@okta/okta-react-native#cleartokens)?

**Comment by FeiChen-okta** [comment]
@jdnichollsc Yes that would be the equivalent of `clearData` in this library.
