### ISSUE TITLE
Invalid Discovery Document

### ISSUE THREAD

**Issue by swagatdishri** [okta/okta-oidc-android#138]
Hi @FeiChen-okta need your help in following case
Getting "Invalid Discovery Document"  when trying to login  from signed apk,otherwise working perfectly.

i have added this in build.gradle for re;lease version
 buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

if we disable  this it is working but it is not recommended.

Looking for any solutions.

**Comment by FeiChen-okta** [comment]
Hi @swagatdishri R8 or proguard is probably causing this issue. The OIDC config is serialized using gson. Try adding the following to the proguard rules
-keep class com.okta.oidc.** { *; }
