### ISSUE TITLE
Unit test using AuthorizationException causes RuntimeException

### ISSUE THREAD

**Issue by timmiller17** [okta/okta-oidc-android#142]
I have a class in my project that accesses the AuthorizationException code field. When I instantiate my class in my unit tests, I get the following error:

`RuntimeException: Method put in android.util.ArrayMap not mocked. See http://g.co/androidstudio/not-mocked for details.`

I believe I have a solution and will open a PR shortly.

**Comment by FeiChen-okta** [comment]
@timmiller17 https://github.com/okta/okta-oidc-android/releases/tag/1.0.10
