### ISSUE TITLE
Using Web view after authentication

### ISSUE THREAD

**Issue by CharlesMcD** [okta/okta-oidc-android#147]
Is there a way to open an Android WebView containing the token or all the things necessary for authentication to avoid having to log back in each time the user opens a new webView?
I log in using `WebAuthClient.signIn()` and I've access to the idToken, accessToken and refreshToken.

**Comment by FeiChen-okta** [comment]
Hi @CharlesMcD The session cookie is not shared with android WebViews, this library uses chrome custom tabs to open the log in page. As of now we have no way to get the cookies from CCT and set it in webviews cookie jar. Please see:
https://bugs.chromium.org/p/chromium/issues/detail?id=539240

A workaround would be to replace web view with CCT.

**Comment by anantrao07** [comment]
just following up in this thread is there way we can extend the session or use the access token received from custom sign in okta flow and use that access token  in webview as head ("Authorization": "Bearer <token>) and retain the user session in webviews?

**Comment by Nagendra6209** [comment]
@anantrao07  Did you get any solution.  after authentication  I want to load the web view

**Comment by anantrao07** [comment]
Sorry unfortunately i didn't get a solution for this.
