### ISSUE TITLE
Android login with browser localization problem

### ISSUE THREAD

**Issue by bedirguven** [okta/okta-oidc-android#148]
In iOS side we use "ui_locales" property for opening login web site on selected language in browser. Android side i added "ui_locales" property to configuration json but login web site always opening english.How can i open login page in selected language. Is there any different configuration in Android for this case.

**Comment by FeiChen-okta** [comment]
Hi @bedirguven Try using the payload:
```java
AuthenticationPayload payload = new AuthenticationPayload.Builder()
    .addParameter("ui_locales", "yourLocale")
    .build();

client.signIn(this, payload);
```

**Comment by jasmineelamblakatt** [comment]
Hi @bedirguven, can u pls just suggest how did to change the locale for the iOS app?
For iOS where to apply the "ui_locales" property in configuartion.
Thanks.
