### ISSUE TITLE
Chrome dependency

### ISSUE THREAD

**Issue by alexzaitsev** [okta/okta-oidc-android#150]
Is it possible to use `WebAuthClient` for authorization but with my own WebView?
I want to keep this flow but get rid of Google Chrome dependency.

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev This a use case that is not currently supported. The WebAuthClient must use chrome custom tabs supported browser as the relaying party. Can you expand on the reason why this is needed?

**Comment by alexzaitsev** [comment]
@FeiChen-okta because not all the devices have Chrome pre-installed.

**Comment by FeiChen-okta** [comment]
@alexzaitsev Good point. Does your devices have other chrome custom tab enabled browsers? I'll set this as an enhancement and discuss internally.

**Comment by alexzaitsev** [comment]
There are no Chrome custom tab enabled browsers. That's why the only approach that is left for now is native sign-in but it has a set of disadvantages (MFA, manual implementation of "forgot password"? and so on). 
Taking all this into consideration, custom WebView would be a nice possibility to keep the current flow.

**Comment by alexzaitsev** [comment]
We had internal discussion and decided that this is a critical point for our release plan. I'm going to play with it and replace Chrome C.T. with custom WebView. 
Please keep me updated about any news.

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev to help us prioritize, can you provide more info on the application? Such as name and what is it used for?

In the mean time I have a few suggestions but have not tested. I would imagine that you would have to do something like the following:
- leave the `appAuthRedirectScheme` empty in your gradle file so OktaAuthenticationActivity does not intercept the redirect.
- Add the scheme to the activity that you want to receive the redirect.
- Provide a custom Configuration when setting up `WebAuthCleint`. You can find your configuration information by going to the discovery uri in your browser.
```java
        mOidcConfig = new OIDCConfig.Builder()
            //... other setup
                .customConfiguration("your custom config")
                .create();
```
- Open WebView to the login page.
after a successful sign-in WebView should send the same uri redirect and payload as CCT.
Your activity should intercept this and you can pass the payload to `WebAuthClient`
by calling `handleActivityResult`. This way you are by passing `OktaAuthenticationActivity` and using `WebAuthClient` to parse the results of the redirect payload.

**Comment by alexzaitsev** [comment]
This information is under NDA, the app is for internal use of store workers of the chain of American stores. Hope it's enough (if not - we can continue private discussion).
I'm trying to make it work using your approach but get the next error:
```
AuthorizationException: {"type":4,"code":4001,"error":"invalid_redirect_uri","errorDescription":"No uri registered to handle redirect or multiple applications registered"}
```
Is there any workaround without changing the sources?

**Comment by FeiChen-okta** [comment]
1. Try adding a fake uri to `appAuthRedirectScheme` The SDK does a null check on that so it is causing the exception.
2. You can use any activity to receive the uri redirect but you may want to keep the activity that hosts the WebView separate `android:exported="false"`. Use a redirectActivity that receives the redirect and pass it a long. This is to prevent other apps from calling the activity that host the webview, which may be doing other things.
3. Yes once you have received the intent you can call `handleActivityResult`. which will do the code exchange and get an access token.

**Comment by alexzaitsev** [comment]
1. I'm trying but get the same `AuthorizationException`...
```
    android.defaultConfig.manifestPlaceholders = [
            "myAuthRedirectScheme": "com.fake.url", // prevent using OktaRedirectActivity
            "nspAuthRedirectScheme": "com.mydomain"
    ]
```
What am I doing wrong?

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev are you calling `signIn` with the `WebAuthClient`? If you are it will throw that exception. Once `OIDCConfig` and `WebAuthClient` is setup you can by pass `signIn` since that will check the redirect_uri is correct in the json file.
signIn downloads the provider configuration and starts chrome custom tabs but you don't need those.
So after the setup you want start WebView to your login page. After a successful login it should redirect to your activity. you use WebAuthClient that was created before to parse the intent data and do PKCE.

**Comment by alexzaitsev** [comment]
@FeiChen-okta I'm still missing something...
As far as I understood I need to open my activity with the WebView instead of `WebAuthClient.singIn()` and load my Okta authorization endpoint to it?
It opens a web page with 400 error
![Screenshot_1584976089](https://user-images.githubusercontent.com/2372414/77331314-38aa6800-6d29-11ea-9731-2bcdbfa9f5d2.png)

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev After looking at your error. It seems the easiest route is to modify OktaAuthenticationActivity in the sdk and add a webview if no browsers found on the bindAndStart method. The reason is that `signIn` call in `WebauthClient` does a lot more than start CCT. For reference it is composing the request parameters for the authorize endpoint https://developer.okta.com/docs/reference/api/oidc/#authorize

**Comment by alexzaitsev** [comment]
Hi @FeiChen-okta 
I see. Ok, I've added the sources to my app and placed similar code to `OktaAuthenticationActivity`:
```
        setContentView(R.layout.activity_okta_auth);
        WebView webView = findViewById(R.id.webView);
        WebSettings settings = webView.getSettings();
        settings.setJavaScriptEnabled(true);

        if (mAuthUri != null) {
            Map<String, String> headers = new HashMap<>();
            headers.put(X_OKTA_USER_AGENT, USER_AGENT_HEADER);
            webView.loadUrl(mAuthUri.toString(), headers);
            webView.setWebViewClient(new WebViewClient() {
                @Override
                public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
                    if (request.getUrl().toString().startsWith("com.mydomain")) {
                        // how to construct an Intent here?
                        return true;
                    }
                    return super.shouldOverrideUrlLoading(view, request);
                }
            });
        }
```

Now I have the next issue - `OktaRedirectActivity` is not catching the Intent and the whole flow is stuck on this step.
Could you help with it? I think that I should construct the intent by myself somehow and send it using `OktaAuthenticationActivity.sendResult` method.

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev try doing the following:

```java
webView.setWebViewClient(new WebViewClient() {
            public boolean shouldOverrideUrlLoading(WebView view, String url){
                Intent redirect = new Intent(Intent.ACTION_VIEW);
                redirect.setData(Uri.parse(url));
                startActivity(redirect);
                return true;
            }
        });
```

**Comment by alexzaitsev** [comment]
@FeiChen-okta that works!
For now I plan to make local Android library from the modified sources of this library (want to keep them separate from my code to be able to swap it with more recent version when this feature will be implemented). Any updates about this? Will this be implemented at all? I just don't want to get stuck with the current version of the library without updates...

**Comment by FeiChen-okta** [comment]
Hi @alexzaitsev Yes we understand that keeping a separate branch isn't ideal. We are evaluating this solution and will update you if anything changes.

**Comment by coreform** [comment]
https://developer.chrome.com/docs/android/custom-tabs/best-practices/

`**Provide a fallback for when Custom Tabs is not installed** 
Although Custom Tabs is available for the great majority of users, there are some scenarios where a browser that supports Custom Tabs is not installed on the device or the device does not support a browser version that has Custom Tabs enabled.

**Make sure to provide a fallback that provides a good user experience by either opening the default browser or using your own WebView implementation.**
`
