### ISSUE TITLE
OktaAuthenticationActivity leak

### ISSUE THREAD

**Issue by bbenninger** [okta/okta-oidc-android#154]
Leak Canary detects a leak of OktaAuthenticationActivity, via CustomTabsServiceConnection

OktaAuthenticationActivity leaks until the server side GCs stale connections.

**Comment by FeiChen-okta** [comment]
Hi @bbenninger Thank you for your contribution. You would have to sign a CLA from https://developer.okta.com/cla and send that to cla@okta.com in order for us to merge this change. Can you sign the CLA and send that to us? Thank you.

**Comment by FeiChen-okta** [comment]
Hi @bbenninger Thank you for the SLA. I have merged your change and will make a release shortly.
