### ISSUE TITLE
Can't logout from browser aftter failed login with "access_denied".

### ISSUE THREAD

**Issue by ktigre** [okta/okta-oidc-android#161]
I have simple application.
For login call:
```
val  client = Okta.WebAuthBuilder() 
...
client.registerCallback(resultCallback, activity)
client.signIn(activity, null)
```
sdk open web browser, I enter **user A** wich don't have access to my application in okta and I received expected error:
`AuthorizationException: {"type":1,"code":1002,"error":"access_denied","errorDescription":"User is not assigned to the client application."}`

Then I want login with other **user B**, But can't to do this, because web browser still logined with **user A**. 
I try call ` client.signOutOfOkta(activity)` but it return to me error: `AuthorizationException: {"type":4,"code":5003,"error":"Keys are invalid. Failed to obtain information about key","errorDescription":"Failed to obtain information about key"}`. and this is valid error I don't have any tokens in sdk. 
But problem: I can login in app by any other user, web browser store auth session and I can't reset it. Any solution?

**Comment by FeiChen-okta** [comment]
Hi @ktigre This is a known issue. The browser should not redirect if the user is not assigned to the application. The only workaround I can think of is to disable saving sessions from the server.
