### ISSUE TITLE
Failed to refresh token.

### ISSUE THREAD

**Issue by ktigre** [okta/okta-oidc-android#165]
okta: com.okta.android:oidc-androidx:1.0.12
api version: 27, 28, 29
reproduced on emulators and real devices

Some time when I try to refresh token, I received error `AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"}`

Steps: 
1) in the evening I turn off the emulator (my application opened in this time)
2) in the morning I turn on the emulator (restored to same state without restart system)
3) application make some call to our BE
4) I received error from our BE (token expared) (through the network)
5) I call `client.sessionClient.refreshToken`
6) I received error from okta sdk `AuthorizationException: {"type":0,"code":3,"errorDescription":"Network error"}`

Note: if I wait some second and retry I will received success.

What happed?

**Comment by FeiChen-okta** [comment]
Hi @ktigre It sounds like after the access token expired you get this error when trying to use the refresh token. You need to wait overnight for the access token to expire. Default time out should be 10mins unless you change this in your admin console. Can you try not turning off the emulator and just wait for the access token to expire? I'll try to reproduce this with the sample app.

**Comment by ktigre** [comment]
Hi @FeiChen-okta 
The problem is not that the token was expired. The problem is that I try refresh token and received `Network error`, but all other network call work fine in the same time. This happend **only** when emulator or device spend **several hours** (I don't know exactly time) without any interaction with okta but application and proccess work. Maybe it go to some "sleep mode" and something happend in okta-sdk that why it slowly handle "network connection restored".
Our current configuration for "access token to expire" ~ 5 or 6 minutes.

**Comment by ivan0013** [comment]
Hi all!
I'am in  a similar situation. But in my case the `RequestCallback` from the refresh method is never called when trying to refresh it after several hours after the token expiration. Can it be related to perform the refresh token from a different activity than the one that registered the `RegisterCallback`?

@ktigre  are you in this situation?

**Comment by FeiChen-okta** [comment]
@ivan0013 I couldn't reproduce the issue that @ktigre was running into. But now that you mentioned using different activities. That will cause the issue both of you are encountering. If your activity is destroyed then the callbacks will not trigger. You should register the callback with the activity that is doing the refresh in onCreate. If that activity is destroyed the callback is unregistered. That would explain the behavior when you leave the device on and leave it. I couldn't reproduce this issue with the samples cause it was always initializing in onCreate.

**Comment by ivan0013** [comment]
That makes sense. Thanks for your answer. 

One more question, can we register the callback in several activities at the same time? or would this cause any troubles? For example: I register the callback on the `LoginActivity`, then I register it again on the `UserProfileActivity` which is the next activity. Or should I perform the `unregister` before register a new one?

**Comment by FeiChen-okta** [comment]
You can call `unregister` or you can register a new callback in `UserProfileActivity` It will replace the previous one.

**Comment by zpapez** [comment]
I'm getting a similar issue, but getting `400 Bad Request` upon token refresh.
The callback seems to work fine for me.

**Comment by ajaymourya4** [comment]
@zpapez I am facing the same issue, any solutions?
`AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid status code 400 Bad Request"}`

**Comment by FeiChen-okta** [comment]
Hi @ajaymourya4 @zpapez check if you have "offline_access" set for the scopes.

**Comment by ajaymourya4** [comment]
@FeiChen-okta "offline_access" is already set for scopes and the refresh token is checked as well.

**Comment by FeiChen-okta** [comment]
Hi @ajaymourya4 can you check the following link to see if the refresh token is enabled
https://{yourOrg}/.well-known/openid-configuration?client_id={client_id}
grant types should contain refresh_token

If it is then can you try using the same org configuration with the sample app?

**Comment by JayNewstrom** [comment]
It looks like Fei was able to answer questions on this issue. If something still isn't clear or working, please reopen, comment, or open a new issue. Thanks!

**Comment by konospl** [comment]
@JayNewstrom this is still happening to me (I am using com.okta.android:oidc-androidx:1.0.18)
When my app is opened again after not being used for extended period of time (several days), the access token is expired (I have access token expiration set for one hour and refresh token for 90 days) and my app is trying to refresh access token.
When making an api call to:
authClient.sessionClient.refreshToken() //where authClient is a Okta's default SyncAuthClient implementation.
I am getting "Invalid status code 400 Bad Request" and the only way to recover from this is to clear session and re-login user again. Very frustrating for my users. This is happening consistently on various devices and users. Any idea what is causing this?

**Comment by konospl** [comment]
> I'm getting a similar issue, but getting `400 Bad Request` upon token refresh.
> The callback seems to work fine for me.
> `AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid status code 400 Bad Request"}`

@zpapez have you been able to resolve your issues with: 
`AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid status code 400 Bad Request"}` ?

**Comment by ggrell** [comment]
I've just run into this same issue in emulator. We use Okta oidc 1.0.18.
`AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid status code 400 Bad Request"}` when calling `authClient.sessionClient.refreshToken()`

**Comment by ssawchenko** [comment]
We are seeing the same issue happening on Okta OIDC 1.2.1, was there ever a solution for this? Or at least a clue as to what could be going wrong? We have been using the same logic since May, and this is the first that this issue has popped up.
> AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid status code 400 Bad Request"}

**Comment by ssawchenko** [comment]
To those also experiencing the "400 Bad Request" error I have opened ticket: https://github.com/okta/okta-oidc-android/issues/332

If you have any repo steps or comments, please add them there so we can try to get to the bottom of this :)
