### ISSUE TITLE
Usage requires Java 8

### ISSUE THREAD

**Issue by michaeltnguyen** [okta/okta-oidc-android#170]
Without

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
``` 

The app crashes with `java.lang.BootstrapMethodError`.

Want a PR to update the documentation?

**Comment by FeiChen-okta** [comment]
Hi @michaeltnguyen Thank you for the suggestion. I have updated the readme with the information.
