### ISSUE TITLE
AuthorizationException: Invalid discovery document

### ISSUE THREAD

**Issue by pgulegin** [okta/okta-oidc-android#171]
I am getting the error:
`AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid discovery document"}`

We have Okta set up for iOS/Android and everything was working a few days ago. Currently, iOS works great; 0 issues there.

On the Android side, everything works as expected when I install the application via Android Studio in debug or release mode. And, everything works as expected on the emulators. I only get the error once it has been sent to the Play Store and the application has been downloaded from there.

I have tried cleaning the project, re-uploading it, making sure I am on the latest versions, including the version that was pushed yesterday.
The only thing that might have changed on our side was we added a Custom URL Domain.

Please advise how to continue. Thank you.

**Comment by FeiChen-okta** [comment]
Hi @pgulegin Check your auth server by entering the custom URL on a web browser. It should show the discovery document.

For example if you are using a custom auth server with a server id:
https://{yourDomain}/oauth2/{authServerId}/.well-known/openid-configuration

If you are not using a custom auth server then try:
https://{yourDomain}/oauth2/default/.well-known/openid-configuration

**Comment by pgulegin** [comment]
Hi @FeiChen-okta, thanks for the quick response!

The discoveryUri I am using is "https://{domain}/oauth2/default/.well-known/openid-configuration", but I am using the builder, rather than config.json
Opening the url in the browser does pull up the discovery document.

config = OIDCConfig.Builder()
.clientId("{clientID")
.redirectUri("{scheme}:/login")
.endSessionRedirectUri("{scheme}:/logout")
.scopes("openid", "profile", "email", "offline_access")
.discoveryUri("https://{domain}/oauth2/default/.well-known/openid-configuration")
.create()

**Comment by FeiChen-okta** [comment]
Hi @pgulegin Is the `issuer` in the discovery document the same in the new custom url domain? You can see this in the discovery document from the browser.

If it is then my best guess is during the switch to the custom url domain, play services is restoring an old config because your app was already logged in on that device. The SDK checks if the issuer changed before obtaining a new discovery doc. You can try calling clearData first.

**Comment by pgulegin** [comment]
Hi @FeiChen-okta,

The issuer is the same, yes.
And, as mentioned before, it works on iOS and works on React. Android is just having issues.

So, I just installed the application from the Play Store onto an Android device that has never had this application installed before. And, I am still running into the same issue. Whenever I try to sign in, the webview never actually opens and onError gets called immediately.
Next, I installed the same build on to the same device via Android Studio and everything works as expected.

I am willing to try calling clearData, if you could provide instructions for that. But, I am not sure that is the problem, seeing how a fresh device is having the same issue.

Please advise on how to proceed! Thank you!

**Comment by FeiChen-okta** [comment]
Hi @pgulegin Try setting `android:allowBackup=false` in the manifest if it isn't already. Or you can call

```
        mSessionClient = mWebAuth.getSessionClient();
        mSessionClient.clear();
```
Before calling `signIn`

**Comment by pgulegin** [comment]
Hi @FeiChen-okta 

I set `android:allowBackup="false"`.
And, I call:
```
webAuthClient.sessionClient.clear()
webAuthClient.signIn(this, null)
```

No changes. Installs from Android Studio bring up the login webview, installs from Play Store fail to bring up the webview and I get the same error.

**Comment by FeiChen-okta** [comment]
Can you provide full logs when running the playstore installed version?

**Comment by pgulegin** [comment]
Of course! What is the best way for me to do that?

**Comment by FeiChen-okta** [comment]
You can email me fei.chen@okta.com. txt files are not filtered.

**Comment by pgulegin** [comment]
I sent the email earlier today, please let me know if there are any issues.

Thank you!

**Comment by FeiChen-okta** [comment]
Received. Thank you will send out some debugging steps.

**Comment by pgulegin** [comment]
Hi @FeiChen-okta,

Please let me know when these debugging steps are available!

Thank you.

**Comment by FeiChen-okta** [comment]
Hi @pgulegin I have replied by email last week. It might have got lost in email filters.

I’ve looked at the log and can’t find anything obviously wrong with the application
One thing you can look at is to print out the cause with something like the following:
 ```
@Override
public void onError(@Nullable String msg, AuthorizationException error) {

    Log.d(TAG, error.error +
            " onActivityResult onError " + msg, error.getCause());
}
```
In AuthorizationException get the cause and try to log it. That should print the stacktrace to see where the failure is.
 
If using a real device for testing I would also try using an emulator with play store just to have a device with new google account associated with it.

**Comment by pgulegin** [comment]
Hi @FeiChen-okta 

I never received the email, so it definitely got lost in the email filters.

We have developments! 
I am now getting: 
`java.lang.IllegalArgumentException: authorization_endpoint is missing`

And, just as before, this only happens in the Play Store version. Works on every other version.

This is my config/builder (from above):
```
config = OIDCConfig.Builder() 
                .clientId("{clientId}")
                .redirectUri("{redirectUri}")
                .endSessionRedirectUri("{endSessionRedirectUri}")
                .scopes("openid", "profile", "email", "offline_access")
                .discoveryUri("https://{domain}/oauth2/default/.well-known/openid-configuration")
                .create()
```

Following the discovery URI, it loads correctly and displays the authorization endpoint.
`authorization_endpoint: "https://{domain}/oauth2/default/v1/authorize"`

**Comment by FeiChen-okta** [comment]
Hi @pgulegin this should not be an issue. if you can see the authorize endpoint from the browser. Does is the playstore release build different from the release build you are testing locally? Is proguard configured differently? Can you add the following in proguard: `-keep class com.okta.oidc.** { *; }`

If that still doesn't work you can try using the `CustomConfiguration` instead of discovery_uri endpoint. You can use a `CustomConfiguration.Builder` and fill out the endpoints and add it in `OIDCConfig.Builder`

**Comment by pgulegin** [comment]
Hi @FeiChen-okta 

It should be the same build...? Unless I set something incorrectly, but this is the only config I have in my build.gradle:
```
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
```
I don't have anything else configured. So, I am not sure if proguard is enabled or not.

With all of that being said, login now works after using the `CustomConfiguration`:
```
        config = OIDCConfig.Builder()
                .clientId("{clientId}")
                .redirectUri("{redirectUri}")
                .endSessionRedirectUri("{endSessionRedirectUri}")
                .scopes("openid", "profile", "email", "offline_access")
//                .discoveryUri("https://{domain}/oauth2/default/.well-known/openid-configuration")
                .customConfiguration(
                        CustomConfiguration.Builder()
                                .authorizationEndpoint("https://{domain}/oauth2/default/v1/authorize")
                                .endSessionEndpoint("https://{domain}/oauth2/default/v1/logout")
                                .introspectionEndpoint("https://{domain}/oauth2/default/v1/introspect")
                                .jwksUri("https://{domain}/oauth2/default/v1/keys")
                                .registrationEndpoint("https://{domain}/oauth2/v1/clients")
                                .revocationEndpoint("https://{domain}/oauth2/default/v1/revoke")
                                .tokenEndpoint("https://{domain}/oauth2/default/v1/token")
                                .userInfoEndpoint("https://{domain}/oauth2/default/v1/userinfo")
                                .create()
                )
                .create()
```
So, good news! Super weird that it is not working with the `discoveryUri()`.

But, now I have a new issue.
Inside `webAuthClient.registerCallback`, inside the `override fun onSuccess(@NonNull status: AuthorizationStatus)`
It appears that when I call:
`val tokens = webAuthClient.sessionClient.tokens`
I get this error in my logcat and my application crashes:
```
07-29 18:36:46.740 19091 19091 D AndroidRuntime: Shutting down VM
07-29 18:36:46.740 19091 19091 E AndroidRuntime: FATAL EXCEPTION: main
07-29 18:36:46.740 19091 19091 E AndroidRuntime: Process: {applicationUri}, PID: 19091
07-29 18:36:46.740 19091 19091 E AndroidRuntime: java.lang.NumberFormatException: s == null
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:570)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:643)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.okta.oidc.q.<init>(Unknown Source:16)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.okta.oidc.r.e.k.a(Unknown Source:12)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.okta.oidc.r.e.h.a(Unknown Source:2)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at org.pwga.mobile.MainActivity$c.e(Unknown Source:54)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at org.pwga.mobile.MainActivity$c.a(Unknown Source:2)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.okta.oidc.r.f.v.n(Unknown Source:6)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.okta.oidc.r.f.m.run(Unknown Source:4)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
07-29 18:36:46.740 19091 19091 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```
Again, this call worked previously. And, again, this call works on my local builds, just not on the Play Store build.

**Comment by FeiChen-okta** [comment]
Hi @pgulegin From the logs, the sources are being obfuscated. Check your project directory for `proguard-rules.pro` file and add `-keep class com.okta.oidc.** { *; }`

More information can be found on https://developer.android.com/studio/build/shrink-code

**Comment by pgulegin** [comment]
Hi @FeiChen-okta,

That fixed everything.
It appears that, by default, when submitting your app, everything gets shrunk/obfuscated/optimized, even if you did not configure it to do so. (Where it might not on a local release build.)
I originally did not have any proguard rules in place or anything in my build config to use proguard rules. But, after adding in the config and creating a `proguard-rules.pro` file, everything worked.

Glad to see that it is now in the README. Maybe let users know to create a `proguard-rules.pro` file, if they don't already have one? But either way, thanks for your help!
