### ISSUE TITLE
Refresh token throwing exception.

### ISSUE THREAD

**Issue by gopalp1709** [okta/okta-oidc-android#178]
Hi ,
I am using refersh token to get new session but I am getting following exception.

**AuthorizationException: {"type":0,"code":0,"errorDescription":"No refresh token found"}**

I am using browser singin and don't want to prompt browser singin to user when session expires.

**Comment by FeiChen-okta** [comment]
Hi @gopalp1709 do you have "offline_access" scope?

**Comment by gopalp1709** [comment]
Hi Fei Chen,

I have added offline_scope in OKTA OIDC json file. Also refresh token lifetime is unlimited.

Thanks
Amol

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FeiChen-okta** [comment]
Check your apps config in the admin console.  Refresh token grant type must be enabled, like the following:
![Screen Shot 2020-08-06 at 3 20 40 PM](https://user-images.githubusercontent.com/46411069/89588449-81eee600-d7f8-11ea-95c2-18a3f0893227.png)

**Comment by gopalp1709** [comment]
After enabling above setting and commenting clear storage in exceptions ,it;s working. Thanks 👍
