### ISSUE TITLE
No certificates found in Chrome when using WebAuthClient

### ISSUE THREAD

**Issue by brianyehsonos** [okta/okta-oidc-android#182]
On some Android OS 8 and 9 devices, Chrome asks for a certificate when the browser is launched for Sign in using `WebAuthClient`. Before the Sign In page is displayed, the user gets a modal requesting a certificate. If the user taps on ""Install certificate"", they're taken to a folder with nothing in it. The dialog states:

No certificates found
The app Chrome has requested a certificate. Choosing a certificate will let the app use this identity with servers now and in the future. The app has identified the requesting server as <_URL_>, but you should only give the app access to the certificate if you trust the app."
 
**Environment**: 
SDK: com.okta.android:oidc-androidx:1.0.13
Devices:
- Samsung Galaxy Tab A (Android 8)
- LG V30 (Android 9)

Is anyone familiar with this issue? We're unsure if this is a device configuration or SDK problem. Thanks!

**Comment by FeiChen-okta** [comment]
Hi @brianyehsonos What is the authorize url that is having this issue? You can check by going to the browser options and click on info. It should show something like:
Also you can copy this url and open chrome and paste the url on your device to see if it also get the certificate issue.

![Screen Shot 2020-08-31 at 1 23 51 PM](https://user-images.githubusercontent.com/46411069/91765088-42b07c80-eb8d-11ea-97b1-26d2dbaba80f.png)

**Comment by kelseymcc** [comment]
It looks like the URL displayed in the browser while the certificate modal is triggered is _oauth.test.ws.sonos.com_. I can't get to the Info button in browser without dismissing the modal. After dismissing, the URL is _https://login-test.sonos.com_

**Comment by FeiChen-okta** [comment]
Hi @kelseymcc I can reproduce your issue by using Android 6 emulator and entering `https://oauth.test.ws.sonos.com` on the browser. This isn't an SDK issue since it seems the root certificate is missing. Contact your certificate provider to check what certificate or intermediate certificates are needed for your site.

![Screen Shot 2020-09-01 at 11 54 30 AM](https://user-images.githubusercontent.com/46411069/91894295-52da6180-ec4a-11ea-980b-dba8bf2165ec.png)

**Comment by brianyehsonos** [comment]
Hi @FeiChen-okta, thanks for the quick turnaround time. Like you said, this is an issue on our side so I'll close this. Thanks for your help!
