### ISSUE TITLE
Password Reset Call - Dying without any response

### ISSUE THREAD

**Issue by aminner** [okta/okta-oidc-android#187]
Good Morning,

We recently identified an issue with native password reset call not doing anything. 

After troubleshooting, we can see the request go out, but a response is never received.

The following is what we're using to make the call: 

`authenticationClient.changePassword(oldPassword.toCharArray(), password.toCharArray(), stateToken, new AuthenticationStateHandlerAdapter(){} `

We've implemented every overrideable method in AuthenticationStateHandlerAdapter to catch the response, but nothing ever happens; break points aren't hit, logs aren't written too. 

As always any guidance is super appreciated!

**Comment by FeiChen-okta** [comment]
Hi @aminner is this for a password expiration? Or password reset?
For password expiration flow see
https://developer.okta.com/docs/reference/api/authn/#authentication-operations
You must perform primary auth and the state should be password_expire then you can call the changePassword.

For password reset it is covered in the recovery flow:
https://developer.okta.com/docs/reference/api/authn/#recovery-operations
For users to reset the password they must go through email/sms/etc.

**Comment by hansreichenbach-okta** [comment]
@aminner also that method call should be returning an `AuthenticationResponse` object as well you can check for information about what is happening.

**Comment by aminner** [comment]
@hansreichenbach-okta  - the issue is, the call is not responding at all. We see the call go out and then it just doesn't return. We know it was working Jan/Feb of this past year, but recently, in the last month or so, uncovered it's no longer providing a response, and thus our password_expired behavior no longer works correctly. 

In the past, we've been successful in tracking down these issues, by stepping through the referenced package code, but so far that has not been the case here.

**Comment by FeiChen-okta** [comment]
@aminner What is the version of authn sdk and the devices that has this issue? Is it on all devices?
Has the sign-in policy changed in the last month? For example if for primary auth did you turn on MFA. The first thing is to check if primary auth works and the response of that sign in call.

**Comment by aminner** [comment]
@FeiChen-okta - all other authn calls are working as intended, it's just this one. It's just weird. We're currently in production with 0.4.0; however I've run through testing this with the newest release as well with the same results. Let me get some logs and will post them when I get them.

**Comment by JayNewstrom** [comment]
Hi @aminner were you able to send us logs for this?
