### ISSUE TITLE
Android 11 gives "No compatible browser found" error

### ISSUE THREAD

**Issue by josephdephillipo** [okta/okta-oidc-android#189]
Updated a phone and created an emulator for Android 11.  Both have Chrome installed and Chrome set to default browser and library version "com.okta.android:oidc-androidx:1.0.16".

When trying to sign in I get the no compatible browser error when previously on Android 10 it worked fine.

`            webAuthClient = WebAuthBuilder()
                    .withConfig(config)
                    .withContext(application)
                    .withTabColor(ContextCompat.getColor(application.applicationContext, R.color.blue))
                    .setRequireHardwareBackedKeyStore(false)
                    .withStorage(SharedPreferenceStorage(application))
                    .create()`

Adding  `.browserMatchAll(true)` and `supportedBrowsers(different combinations based on ReadMe)` doesn't seem to do anything.

Maybe this could be the issue?
https://developers.google.com/web/updates/2020/07/custom-tabs-android-11
https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by josephdephillipo** [comment]
Updated our app's gradle version and adding 
`    <queries>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>`
to the manifest worked 👍

**Comment by FeiChen-okta** [comment]
Hi @josephdephillipo I'm glad that it worked. We are still in the process of testing SDK 30 changes.

**Comment by ryanjwessel** [comment]
For those that encounter this problem on Android 11, I can confirm that the fix @josephdephillipo posted works.

In our case, we are maintaining a React Native application. This required us to upgrade Android Gradle to 4.1.2, Gradle to 6.5, Android build tools to 29.0.2, and React Native to 0.63.4.

I'm not sure what the state of Android 11 research is for Okta, but could this solution be added to the documentation somewhere (if it isn't already)?

**Comment by NikitaAvraimov-okta** [comment]
> For those that encounter this problem on Android 11, I can confirm that the fix @josephdephillipo posted works.
> 
> In our case, we are maintaining a React Native application. This required us to upgrade Android Gradle to 4.1.2, Gradle to 6.5, Android build tools to 29.0.2, and React Native to 0.63.4.
> 
> I'm not sure what the state of Android 11 research is for Okta, but could this solution be added to the documentation somewhere (if it isn't already)?

It was fixed, you can check out our ANdroidManifest https://github.com/okta/okta-oidc-android/blob/master/library/src/main/AndroidManifest.xml

**Comment by ryanjwessel** [comment]
Awesome, thanks @NikitaAvraimov-okta!

I see that Okta React Native is still one patch version behind this update. I can mention it in that repository instead.
