### ISSUE TITLE
Invalid_scopes: Custom scopes are not allowed for this request

### ISSUE THREAD

**Issue by Nanstop** [okta/okta-oidc-android#190]
I can successfully sign in following the sample code with the three default scopes ["openid", "profile", "offline_access"], however our backend API requires additional custom scopes such as: "companies:read", "files:read", "files:write" etc. defined in a Okta Authorization Server. I updated the discovery Uri from https://xxxx.oktapreview.com to https://xxxx.oktapreview.com/oauth2/server_id/.well-known/oauth-authorization-server which points to the json with all the config/scope needed. But I always get Custom scopes are not allowed for this request. And I see nobody else on the internet attempted with a custom scope using okta-oidc-android lib. Please let me know if this is supported or what is the correct lib to use.

Thank you very much.

**Comment by Nanstop** [comment]
Just want to provide more information: 
1. Our oauth authorization server grants all the custom scopes mentioned
2. Scope.java in okta-oidc-android only has the generic scopes (email, phone, openid etc.) defined in the class, the rest will throw assertion error.
3. Is there a different auth request that works with custom scopes provided by okta-oidc-android but I am not aware?

**Comment by FeiChen-okta** [comment]
Hi @Nanstop Scope.java is only a convenience for generic scopes. for example it can be used when initializing the oidc config.
```
        config = new OIDCConfig.Builder()
                .clientId(BuildConfig.CLIENT_ID)
                .redirectUri(BuildConfig.REDIRECT_URI)
                .endSessionRedirectUri(BuildConfig.END_SESSION_URI)
                .scopes(Scope.OPENID, Scope.EMAIL, "my.custom.scope")
                .discoveryUri(BuildConfig.DISCOVERY_URI)
                .create();
```

For your custom scopes. have you added it to the config builder? Or the json file if you are using it?

**Comment by Nanstop** [comment]
Hi FeiChen,

Thank you for fast respond. My OIDC config is as following:
val oidcConfig = OIDCConfig.Builder()
            .clientId("client_id")
            .redirectUri("com.oktapreview.company_id:/callback")
            .endSessionRedirectUri("com.oktapreview.company_id:/")
            .scopes("openid", "profile", "offline_access", "companies:read", "files:read", "files:write", "me", "email")
            .discoveryUri("https://compay_id.oktapreview.com/oauth2/auth_server_id")
            .create()

        webAuth = Okta.WebAuthBuilder()
            .withConfig(oidcConfig)
            .withContext(applicationContext)
            .withCallbackExecutor(null)
            .withEncryptionManager(DefaultEncryptionManager(this))
            .setRequireHardwareBackedKeyStore(false)
            .create()
And my console logs the following:
D/MainActivity: invalid_scope onError
    AuthorizationException: {"type":1,"code":1004,"error":"invalid_scope","errorDescription":"Custom scopes are not allowed for this request."}
        at com.okta.oidc.AuthenticationResultHandler.retrieveResponse(AuthenticationResultHandler.java:100)
        at com.okta.oidc.AuthenticationResultHandler.handleAuthenticationResult(AuthenticationResultHandler.java:81)
        at com.okta.oidc.AuthenticationResultHandler.onActivityResult(AuthenticationResultHandler.java:70)
        at com.okta.oidc.OktaResultFragment.onActivityResult(OktaResultFragment.java:110)

When I debug into your lib, I can see the auth request object as following:
1. scope has all the custom scopes
2. authorize_endpoint is https://company_id.oktapreview.com/oauth2/v1/authorize
3. client id/redirect_uri both matches my okta application.
4. code_challenge_method is S256 not sure if this is correct

**Comment by FeiChen-okta** [comment]
Hi @Nanstop,

If you can check your auth server's rules from 
https://help.okta.com/en/prod/Content/Topics/Security/API_Access.htm#
under `How do I set up an authorization server?` and `Create Rules for Each Access Policy`
Check if your server have the correct rules and access policy for the user you are using to sign in with.

**Comment by Nanstop** [comment]
@FeiChen-okta,

 I pulled out the json of our oauth auth server's configuration as following:

{"issuer":"https://company_id.oktapreview.com/oauth2/auth_server_id","authorization_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/authorize","token_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/token","registration_endpoint":"https://company_id.oktapreview.com/oauth2/v1/clients","jwks_uri":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/keys","response_types_supported":["code","token","id_token","code id_token","code token","id_token token","code id_token token"],"response_modes_supported":["query","fragment","form_post","okta_post_message"],"grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"subject_types_supported":["public"],"scopes_supported":["companies:read","files:read","files:write","me","openid","profile","email","address","phone","offline_access"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt","private_key_jwt","none"],"claims_supported":["ver","jti","iss","aud","iat","exp","cid","uid","scp","sub"],"code_challenge_methods_supported":["S256"],"introspection_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/introspect","introspection_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt","private_key_jwt","none"],"revocation_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/revoke","revocation_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post","client_secret_jwt","private_key_jwt","none"],"end_session_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/logout","request_parameter_supported":true,"request_object_signing_alg_values_supported":["HS256","HS384","HS512","RS256","RS384","RS512","ES256","ES384","ES512"]}

You can see the supported scopes has all the custom scopes including access_offline, and I double checked my Okta account for my android app has the okta.authorizationServers.read granted under Okta API Scopes, and for the Access Policies of our auth server, my android app is surely granted access.

So I am not sure why there is still custom scope not allowed for calling oauth/v1/authorize in my case.

**Comment by Nanstop** [comment]
Also just FYI, when I tested "Token Preview" under our auth server with a custom scope (companies:read), I can see the preview with a generated token. This must mean things are configured correctly for our auth server.

**Comment by FeiChen-okta** [comment]
Hi @Nanstop 

Can you check the following json returned?
https://${yourOktaDomain}/oauth2/${authServerId}/.well-known/oauth-authorization-server?client_id={yourClientId}

**Comment by Nanstop** [comment]
@FeiChen-okta,

Here is the json returned. I noticed the difference many properties:  

{"issuer":"https://company_id.oktapreview.com/oauth2/auth_server_id","authorization_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/authorize","token_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/token","registration_endpoint":"https://company_id.oktapreview.com/oauth2/v1/clients/client_id","jwks_uri":"https://companye_id.oktapreview.com/oauth2/auth_server_id/v1/keys","response_types_supported":["code"],"response_modes_supported":["query","fragment","form_post","okta_post_message"],"grant_types_supported":["authorization_code","refresh_token"],"subject_types_supported":["public"],"scopes_supported":["companies:read","files:read","files:write","me","openid","profile","email","address","phone","offline_access"],"token_endpoint_auth_methods_supported":["none"],"claims_supported":["ver","jti","iss","aud","iat","exp","cid","uid","scp","sub"],"code_challenge_methods_supported":["S256"],"introspection_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/introspect","introspection_endpoint_auth_methods_supported":["none"],"revocation_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/revoke","revocation_endpoint_auth_methods_supported":["none"],"end_session_endpoint":"https://company_id.oktapreview.com/oauth2/auth_server_id/v1/logout","request_parameter_supported":false}

**Comment by FeiChen-okta** [comment]
Hi @Nanstop That looks correct. The only thing i suggest you check is the access policy. 
https://support.okta.com/help/s/article/Difference-Between-Okta-as-An-Authorization-Server-vs-Custom-Authorization-Server?language=en_US&_ga=2.132402254.178261791.1602181167-1529871466.1589992623

Check the Access policies section. your scopes should include all your custom scopes for example for my authorization server I have `myscope`

![Screen Shot 2020-10-09 at 2 08 45 PM](https://user-images.githubusercontent.com/46411069/95631806-27ad1400-0a39-11eb-95ff-27cac087b9de.png)

**Comment by Nanstop** [comment]
@FeiChen-okta ,
I found the issue, after I put a breakpoint in your AuthorizeRequest.java to exam the request object before make the request, I found out the request url was https://company_id.oktapreview.com/oauth/v1/authorize, the auth server id was missing from the url, so I replaced the discovery_uri property with CustomConfig object and specific the exact url for each endpoint based on https://${yourOktaDomain}/oauth2/${authServerId}/.well-known/oauth-authorization-server?client_id={yourClientId} and it worked!! 

Thank you so very much for the help. With this obstacle removed, our ideal architecture can happen:
multiple Okta app accounts (web/native) <-> Single Okta Auth server < -> Single backend API instance <-> multiple client side (web/iOS/Android)

Much appreciated.

**Comment by nasreekar** [comment]
@Nanstop  @FeiChen-okta Despite using custom config object im still seeing the custom_scopes error message. is there anything else i need to look into to fix this? This happens only on android and not ios. 

Also is there a way to print the auth request url before launching the browser ? i dont seem to find a way to do so.

**Comment by FeiChen-okta** [comment]
Hi @nasreekar check that you hitting the correct server, go to the endpoint
 https://${yourOktaDomain}/oauth2/${authServerId}/.well-known/oauth-authorization-server?client_id={yourClientId}
and check that scopes_supported array contains your custom scopes.
