### ISSUE TITLE
ISS from returned Access Token not configurable

### ISSUE THREAD

**Issue by Nanstop** [okta/okta-oidc-android#191]
Following the sample code I can successfully authenticate an Android user. But I am getting a  org.openapitools.client.infrastructure.ClientException: {
      "detail": "Signature verification failed.",
      "status": 400,
      "title": null,
      "type": "about:blank"
    }
returned from an API GET request made to our backend using the returned access token for API authentication.

When I later exam the parsed access token I found out the ISS (issuer url) is: https://company_id.oktapreview.com, though I set the discovery_uri to be https://company_id.oktapreview.com/oauth2/auth_server_id. Our backend upon receiving an incoming request will first verify the signature (a number of things from the access token and ISS is one of them). Since the ISS does not match therefore 400 returned.

How to set the issuer_url from this library? In okta-vue for web-app the issuer property is available.

Please help me, thank you

**Comment by FeiChen-okta** [comment]
Hi @Nanstop,

The access token is minted by your auth server. You can't change this in the client SDK. So if the issuer is incorrect it is the auth server configuration that needs to be updated. You can check the following
https://help.okta.com/en/prod/Content/Topics/Security/API_Access.htm#

Under that section should be a `Test Your Authorization Server Configuration` which you can use to preview the tokens and see if your server configuration matches what you expect.

**Comment by Nanstop** [comment]
With the correct okta auth server config implemented (use CustomConfig property in the OIDCConfig class instead of Discovery_uri), this problem no longer exists.

Thank you for your help @FeiChen-okta
