### ISSUE TITLE
SignIn via Web Auth fails in Emulator

### ISSUE THREAD

**Issue by RichiCoder1** [okta/okta-oidc-android#192]
Background Note: I'm calling this lib via Okta's React Native lib. However, I'm pretty sure the issue is with this lib and not React Native or Okta's Lib for React Native.

Long story short, calling `signIn()` which in turn calls `webClient.signIn(currentActivity, null)` does nothing. I can see the call be made to the discovery endpoint, but nothing happens after that. No errors, no exceptions in logcat, nothing. Not sure if I'm doing something wrong or if something's broken.

The same operation with the same app works fine when running with an actual device.

**Comment by FeiChen-okta** [comment]
Hi @RichiCoder1 you should get a onError callback propagated back to the application. This depends on how you are handling the errors. You can try the sample app and see if the error dialog shows up.

A few things can happen when running on the emulator.
1. Check if the chrome browser or any chrome custom tab compatible browser is installed.
2. Check your config to see if `requiredHardwareBackedKeyStore` is set to false. Emulators does not have hardware keystores. An example config https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#createconfig

**Comment by RichiCoder1** [comment]
> Hi @RichiCoder1 you should get a onError callback propagated back to the application. This depends on how you are handling the errors. You can try the sample app and see if the error dialog shows up.

I'll give this a try and see if a basic sample app still has issues. Might be an issue unique to my setup.

> Check if the chrome browser or any chrome custom tab compatible browser is installed.

It's a stock emulator image with Google Play Services & Chrome, so that's not it.

> Check your config to see if requiredHardwareBackedKeyStore is set to false. Emulators does not have hardware keystores. An example config https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#createconfig

That was my first instinct, but this flag didn't seem to have an effect either way. Have it hard coded to false for now.

**Comment by JayNewstrom** [comment]
Hi @RichiCoder1 are you still experiencing this issue? Is there anything else we can do to help resolve it?

**Comment by RichiCoder1** [comment]
We are indeed. I'll see if I can get a reproducible example and maybe some actionable details. Basically makes it currently impossible to Dev our React Native app in an android emulator atm.

**Comment by JayNewstrom** [comment]
I'm able to use our [react native samples](https://github.com/okta/samples-js-react-native/) on an Android emulator.

If you can get us a way to reproduce or more details that would be great!

**Comment by ghana7989** [comment]
I still face this issue, in the emulator I can not develop and connecting to mobile phone always is an issue
