### ISSUE TITLE
Question: In what cases should `RequireHardwareBackedKeyStore` be set to true?

### ISSUE THREAD

**Issue by broccolibird** [okta/okta-oidc-android#195]
In the SampleActivity, `setRequireHardwareBackedKeyStore()` is set to true when the device is not an emulator:
`.setRequireHardwareBackedKeyStore(!isEmulator())`

https://github.com/okta/okta-oidc-android/blob/master/app/src/main/java/com/okta/oidc/example/SampleActivity.java#L440

However `isEmulator()` will return true if the device's manufacturer is "Google", which is true for all of the Pixel devices. In what cases should `setRequireHardwareBackedKeyStore()` be true? If we are using the default storage can we safely set this value to false?

**Comment by FeiChen-okta** [comment]
Hi @broccolibird `isEmulator` probably needs an update with the recent pixel devices. Emulators don't support hardware keystore so this is main to allow the sample to run on emulators. Some devices does not support hardware keystore but these are really old devices. I would recommend leaving it to `true` when running on real devices and false on emulators. More information on key extraction https://developer.android.com/training/articles/keystore#ExtractionPrevention

**Comment by broccolibird** [comment]
Thank you for the quick response, @FeiChen-okta .

We have a user who cannot login because their device does not have the correct support. If we set the field to false, the devices that have support will continue to use the hardware backed keystore, correct?

**Comment by FeiChen-okta** [comment]
Hi @broccolibird That flag is global. You can do something similar to `isEmulator` check and set it to false on devices that does not have hardware keystore support. I think any device with API < 23 should be set to false. Or you can compile a list of devices that does not have hardware support. 

Another way to dynamically check is to create a key in your application and use the KeyInfo https://developer.android.com/reference/android/security/keystore/KeyInfo#isInsideSecureHardware()
This requires initial key creation using android keystore.

**Comment by broccolibird** [comment]
> If we set the field to false, the devices that have support will continue to use the hardware backed keystore, correct?
>> That flag is global. You can do something similar to isEmulator check and set it to false on devices that does not have hardware keystore support.

I'm debugging this here and it appears that it is still using a hardware backed keystore even when the require flag is set to false. I'm specifically looking at line 76 in OktaRepository where requireHardwareBackedKeyStore has been set to false by me and `encryptionManager.isHardwareBackedKeyStore()` is returning true.

```
if (!requireHardwareBackedKeyStore || encryptionManager != null &&
                    encryptionManager.isHardwareBackedKeyStore()) {
```

Can you verify this or is there something I am missing here?

> I think any device with API < 23 should be set to false. Or you can compile a list of devices that does not have hardware support.
The device with the issue is an API 26 tablet (which is also our minSdk). It would be very difficult to compile a list of devices that do not have the needed support and it is unacceptable that our users would download our app from the play store and not be able to log in.

**Comment by FeiChen-okta** [comment]
Hi @broccolibird Ah yes! you are right. The SDK always defaults to hardware keystore if available. The flag is to set if the application requires it to run. So setting it to false means, it is not required but the SDK will still use it if it is available.

**Comment by broccolibird** [comment]
Thanks again for the quick responses, @FeiChen-okta, and for the confirmation.

**Comment by JayNewstrom** [comment]
Thanks for the issue @broccolibird. It looks like Fei was able to answer your questions. If you have any other questions feel free to reopen this issue, or create a new one.
