### ISSUE TITLE
Issue with androidx & android

### ISSUE THREAD

**Issue by tackanoway35** [okta/okta-oidc-android#208]
I don't want to use androidx and i install com.okta.android:oidc-android:1.0.13 instead of com.okta.android:oidc-androidx:1.0.13 but i found import androidx.annotation.NonNull; inside WebAuthClient.java => error "Can not resolve symbol NonNull"
Can i use "oidc-android" without androidx
Thanks for watching!

**Comment by JayNewstrom** [comment]
Yes, we publish 2 artifacts. Looks like you're on the right track with trying to use `implementation 'com.okta.android:oidc-android:1.0.17'`.

I decompiled the artifact to make sure we weren't publishing with the wrong annotations. 

My guess is that there's an issue with your setup. Could you please provide more information, a sample, or steps to reproduce.

**Comment by tackanoway35** [comment]
I fixed my issue by upgrade all libs to androidx. Thanks for support

**Comment by JayNewstrom** [comment]
No problem. Glad you got everything working!
