### ISSUE TITLE
Issues upgrading from v1.0.11 to v1.0.17

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-android#210]
I'm trying to upgrade our [Android Authentication](https://developer.okta.com/blog/2020/04/20/android-authentication) tutorial to the latest version and I'm having issues making things work. A couple of questions:

1. I'm still targeting API 23. Will that still work with v1.0.17?
2. Do I still need to add the `android.permission.INTERNET` permission?
3. Do I need to add `okta-authn-sdk-api` and `okta-authn-sdk-impl` as dependencies?

I have both of these permissions in my `AndroidManifest.xml`:

```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

When I try to run my app on a Pixel 3 XL API 29 VD, the app shows, but nothing happens when I click the Sign In button. The following does get printed in the Run console in Android Studio:

```
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
```

My `setupWebAuth()` is as follows:

```kotlin
private fun setupWebAuth() {
    val oidcConfig = OIDCConfig.Builder()
            .clientId("0oa2x1v8cYfnXmR3Z5d6")
            .redirectUri("com.okta.dev-6974382:/callback")
            .endSessionRedirectUri("com.okta.dev-6974382:/logout")
            .scopes("openid", "profile", "offline_access")
            .discoveryUri("https://dev-6974382.okta.com")
            .create()

    webAuth = Okta.WebAuthBuilder()
            .withConfig(oidcConfig)
            .withContext(applicationContext)
            .withStorage(SharedPreferenceStorage(this))
            .create()
    sessionClient = webAuth.sessionClient
}
```

You can see my code so far at https://github.com/mraible/android-authentication.

**Comment by JayNewstrom** [comment]
1. The general recommendation is to target the latest android sdk, and to set your minSdk to the lowest you'd like to support.
2. You will need to add `android.permission.INTERNET` to the manifest at least until the next version is released. It's a recent code change I made. But it'll never hurt to add it.
3. The `okta-authn-sdk` SDKs are independent of this one. If you're using those APIs directly, you'll need it, but you won't if you're using this SDK only.

The issue you're running into appears to be that you need to add `.setRequireHardwareBackedKeyStore(false)` to your `WebAuthBuilder` https://github.com/mraible/android-authentication/blob/a5ae14d1a84bc24c413fabfc5fa3dc21108f5fce/app/src/main/java/com/akaita/myapplication/MainActivity.kt#L49 when you're running it on an emulator.

**Comment by mraible** [comment]
Adding `.setRequireHardwareBackedKeyStore(false)` works! 🙏
