### ISSUE TITLE
Feature Request - Trusted Web Activity Support for browser sign-in flows

### ISSUE THREAD

**Issue by maneeshsahu** [okta/okta-oidc-android#213]
We currently use webviews/chrome custom tabs for the browser sign-in flows. 

In 2020, Google announced 'Trusted Web Activity' as an alternative to using WebViews. See: https://developers.google.com/web/android/trusted-web-activity 

Trusted Web Activity allows the shared instance of a browser like Chrome to be utilized for displaying web content (esp Progressive Web Apps). This allows sessions to be shared between native apps and the browser/chrome just like with new tabs in the browser. 

Customers are adopting TWAs for building hybrid apps (that look like native apps). 

We should add support for this.

**Comment by JayNewstrom** [comment]
I agree, this sounds interesting. I've added a task to our backlog to look more deeply into it.

If anyone comes across this issue, and is looking to use this functionality please give it a thumbs up.

Internal Ref: OKTA-358933

**Comment by NikitaAvraimov-okta** [comment]
We found that it is possible to sign in to okta via TWA. 
In order for TWA to work we have to be able to upload a file to
{domain}/.well-known/assetlinks.json
Trusted web activities work only after a digital handshake, we need to be able to add this file which will contain hosting site domain, app package name and a sha-256 package fingerprint to ensure that app publisher indeed owns an app. For testing purposes i skipped validation process and it looks like sign in is working, session is kept and when deleting an application with TWA user is prompted with alert dialog stating that upon deletion some data may still be stored in chrome.

**Comment by maneeshsahu** [comment]
@NikitaAvraimov-okta This is fantastic. Is this something that will be automatically be available to Okta tenants/authorization servers?

**Comment by NikitaAvraimov-okta** [comment]
@maneeshsahu I think it is not, we should talk to okta admin console maintainers.

**Comment by NikitaAvraimov-okta** [comment]
Although I want to point out that twa is mostly used for progressive web apps. PWA developers that use TWA often just specify url of their web site which will be loaded after native application launch. Common use case is when they have a web site and do not have an app, and they want their customers to be able to found an app in the Play Store. Such apps usually come in form of an SPA which will already have some sort of identity management, their spa can even have okta-auth-js integrated and they would not need any further configuration.

**Comment by JayNewstrom** [comment]
We have no plans to integrate TWA, as it's not a good fit for the Native App OAuth use case.
