### ISSUE TITLE
Issues with using the token to login to my local web app

### ISSUE THREAD

**Issue by dbikic** [okta/okta-oidc-android#215]
Hi!

I hope you guys can help me out, I have issues connecting to my web app with the token I've got from this SDK.

Here is what I did:
1) I followed the [Build Reactive APIs with Spring WebFlux](https://developer.okta.com/blog/2018/09/24/reactive-apis-with-spring-webflux) blog post and I've cloned the result [repo](https://github.com/oktadeveloper/okta-spring-webflux-react-example)
2) I've created a web app in the Okta admin interface and I've set it up as per the blog post, and I've started the web app
3) I opened Chrome and navigated to http://localhost:8080/profiles  
4) Okta sign-in interface appeared before me, and after entering my credentials I've managed to successfully access my web app's API
5) My next step was to follow the [Android Login Made Easy with OIDC](https://developer.okta.com/blog/2021/01/06/android-login) blog post
6) I've created a new mobile app in the Okta admin interface (I've noticed that the Okta domain is the same for my web and mobile Okta applications)
7) I've run the Android app, clicked on the sign-in button, got navigated to the Okta sign-in screen, entered the same credentials I've used for logging into the web app, and managed to successfully login
8) After the login, I've got the auth token from the `SessionClient` and tried to access my webserver running on localhost (not that the endpoint I had to use was http://10.0.2.2:8080/profiles because you can't access localhost from the Android emulator)
9) Got an issue which I've resolved by adding `android:usesCleartextTraffic="true"` to the application tag in the AndroidManfiest.xml
10) Tried again to connect to my web app, but without luck. I'm using Retrofit for making the API call, and I'm adding the token as the header of my request like this:
```
Interceptor { chain ->
    val requestBuilder = chain.request().newBuilder()
    requestBuilder.header("Authorization", "Bearer $token")
    chain.proceed(requestBuilder.build())
}
```
And I'm always receiving 401 Unauthorized. I've also tried with Postman, but with the same result.
 
I've tried to debug this a bit more, by running the React app found in the web app's blog-post Github repo, mentioned in step 1). I've opened the React app in an incognito tab, open the Chrome dev tools to inspect the requests, and signed into the Okta app. After the successful login, I've noticed the API call to http://localhost:8080/profiles which had the bearer token in the request headers. I've hardcoded that token in my Android app interceptor and ran the app. I got 200 OK from my backend app, which I guess means the code on the Android side is working ok. Tried again with Postman, and I've also received 200.

Can you please review if there is anything wrong that I'm doing here?

**Comment by JayNewstrom** [comment]
Hi @dbikic thanks for the question. 

Can you please confirm the user is assigned to the application in the okta dashboard?

**Comment by dbikic** [comment]
@JayNewstrom thanks for the quick response!

When I go to the details of that user, I can see that he is added to all my Okta applications:

![image](https://user-images.githubusercontent.com/7935545/107006581-a1f46780-6791-11eb-8235-c225462a280e.png)

And when I try to assign him to a new application, I see this message in the pop up:

![image](https://user-images.githubusercontent.com/7935545/107006720-dc5e0480-6791-11eb-8a37-c67e7f1b6384.png)

**Comment by JayNewstrom** [comment]
Ok, after talking with the team. I think you need to use a custom authorization server to do the token validation.

If you're using the the org authorization server now, would you be willing to try using a custom authorization server?

https://developer.okta.com/docs/concepts/auth-servers/#custom-authorization-server

Could you share the issuer you're using? (you can redact the prefix) It would look something like `https://dev-foo.okta.com/oauth2/aus2l8zi8N7gHwKS55d6` or `https://dev-foo.okta.com/oauth2/default`

You can add an authorization server here: https://dev-yourdevidhere-admin.okta.com/admin/oauth2/as by replacing `yourdevidhere`

**Comment by dbikic** [comment]
I think I'm using a default authorization server. I've tried creating a custom authorization server, but I have no clue how to use it.

So I now have 2 issuers, one is the default one and the other one is the one I've just created:
![image](https://user-images.githubusercontent.com/7935545/107263775-73e97e80-6a42-11eb-92b2-b7ebfb4732d1.png)

I'm not quite sure how to associate this with my two Okta apps (mobile and web).

**Comment by JayNewstrom** [comment]
Can you try using the new authorization server as the issuer for both the web app, and the mobile app? (in place of where you had oauth2/default before.

**Comment by dbikic** [comment]
Finally got a 200! It worked after I've changed the `discoveryUri` when initializing the Android SDK to the new authorization server URL.

Maybe you could improve [this](https://github.com/okta/okta-oidc-android#discovery-uri-guidance) readme section with the info that this is also the issuer URL? I had issue with it, since the naming is different :)

Anyways, thanks a lot for your help @JayNewstrom you helped me a lot!

**Comment by JayNewstrom** [comment]
Will do. I created an internal ticket to update the documentation here: OKTA-368652

I'll close this issue, but feel free to reopen with any other questions.

PS. I'm interested to read the new blog post, so feel free to post here if you'd like :)
