### ISSUE TITLE
accessing code_verifier and code for refreshing token

### ISSUE THREAD

**Issue by andersonknox18** [okta/okta-oidc-android#218]
Is there more documentation about how to access code_verifier and code that is used for getting new access token using refresh token. We are using custom login on native app to work using the PKCE flow. 
In our current use case, after initial login, we persist the refresh token. The user always remains signed in unless they choose to sign out. 

```
 val authClient = OktaMfaConfig().getConfig()?.let {
            Okta.AuthBuilder()
                .withConfig(it)
                .withContext(context)
                .withStorage(SharedPreferenceStorage(context,PREF_STORAGE_AUTH))
                .setRequireHardwareBackedKeyStore(false)
                .create()
        }
```
 In this case, is there a way to access code_verifier and code required to refresh tokens?

**Comment by NikitaAvraimov-okta** [comment]
Hey, general overview can be found here: [link](https://developer.okta.com/docs/guides/implement-auth-code-pkce/overview/). Although you do not really need to generate code_verifier manually - it is handled. Native sign in happens here [AuthClientImpl](https://github.com/okta/okta-oidc-android/blob/9ae24eaac0ee1904821a77731f0648c9cebc72ed/library/src/main/java/com/okta/oidc/clients/AuthClientImpl.java#L69), refreshToken happens [here](https://github.com/okta/okta-oidc-android/blob/9ae24eaac0ee1904821a77731f0648c9cebc72ed/library/src/main/java/com/okta/oidc/clients/sessions/SyncSessionClientImpl.java#L185). You can also describe your use case in more detail.

**Comment by andersonknox18** [comment]
thanks, can we access these values persisted in SharedPreferencesStorage?

**Comment by FeiChen-okta** [comment]
Hi @andersonknox18 you get the the tokens using `sessionClient.getTokens()`

**Comment by JayNewstrom** [comment]
@andersonknox18 please reopen if you have any other questions. Thanks!
