### ISSUE TITLE
"Invalid discovery document" on

### ISSUE THREAD

**Issue by cap-myahmi** [okta/okta-oidc-android#220]
hello  team, 
I followed all the steps how to create the app  and in the end i get  this following error , 
 null onError
    AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid discovery document"}

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for reporting! 

@jaynewstrom-okta Can you help take a look?

**Comment by NikitaAvraimov-okta** [comment]
@cap-myahmi Could you please share some insight on your configuration. You should probably check if you specified correct discoveryUri
<img width="767" alt="image" src="https://user-images.githubusercontent.com/76003913/108518068-d65b3e00-72d0-11eb-848b-510b0f3f3871.png">
You could also refer to https://github.com/okta/okta-oidc-android/issues/132

**Comment by JayNewstrom** [comment]
@cap-myahmi Please reopen with more information. Thanks!
