### ISSUE TITLE
Refresh Token always returning Invalid Token

### ISSUE THREAD

**Issue by kirtipopli83** [okta/okta-oidc-android#222]
Hello Team,

I have implemented Okta SDK in the Android app.
- While using the refresh token method of Okta from sessionClient, I am always getting error as "Invalid ID Token"
- I am not able to figure out, what is actually wrong as the method is not accepting any parameters.

**Comment by NikitaAvraimov-okta** [comment]
Could you please share how do you create your oidc config, do you pass offline_access?

**Comment by kirtipopli83** [comment]
Yes, I have passed offline_access as well.

**Comment by NikitaAvraimov-okta** [comment]
Could you also please check if you allowed grant respective grant type at okta admin dashboard - refresh token should be enabled. I would also need to know which steps do you toke in order to refresh your token

**Comment by kirtipopli83** [comment]
I have return this call in a method

    fun refreshToken() {
        /**Refresh Token*/
        if (mSessionClient == null) {
            mAuthClient = activity?.let { ServiceLocator.provideAuthClient(it) }
            mSessionClient = mAuthClient?.sessionClient
        }

        listener.onLoading()

        if (mSessionClient?.tokens?.isAccessTokenExpired!!){
            mSessionClient?.refreshToken(object :
                RequestCallback<Tokens?, AuthorizationException> {
                override fun onSuccess(tokens: Tokens) {
                       showMessage("Token refreshed successfully") 
                }

                override fun onError(s: String?, e: AuthorizationException) {
                    listener.onError("", e.message.toString())
                }
            })
        }
    }

**Comment by kirtipopli83** [comment]
Any update on this?

**Comment by NikitaAvraimov-okta** [comment]
Looking into it. Still, could you ensure that you enabled refresh token grant type at okta admin board. It would be helpful to see what do you receive at
```
onError(s: String?, e: AuthorizationException)
```

**Comment by NikitaAvraimov-okta** [comment]
@kirtipopli83 what`s in e: AuthorizationException? It would help me as well.

**Comment by kirtipopli83** [comment]
"s" in the onError() is null, while e: AuthorizationException has object in it.

AuthorizationException: {"type":0,"code":9,"errorDescription":"Invalid ID Token"}

**Comment by NikitaAvraimov-okta** [comment]
Check out https://github.com/okta/okta-oidc-android/blob/96761d5e44a0f0dea92c4b9263e891327d148da4/library/src/main/java/com/okta/oidc/OktaIdToken.java#L299
Would you be able to check which validation step throws an error? 
Have you tried introspecting your tokens after successful auth?

**Comment by kirtipopli83** [comment]
Yes, once I get the tokens from session client I am using Introspect() method to check if token is valid, then I handle the further functionality

**Comment by kirtipopli83** [comment]
I tried to search for this method in the sdk but was not able to find such method  "public void validate(TokenRequest request, Clock clock) throws AuthorizationException { }"

**Comment by NikitaAvraimov-okta** [comment]
@kirtipopli83 look for OktaIdToken class

**Comment by kirtipopli83** [comment]
Yes, I got the OktaIdToken class. But how to make use of it? as It asks for parameters in constructor to pass in-order to use validate method.

Also how to create the TokenRequest and what is the use of Clock class in validate method parameter?

**Comment by NikitaAvraimov-okta** [comment]
It has a validation method, it is getting called when token is refreshed. Could you please check which steps throw an error for you putting some breakpoints over there?

**Comment by kirtipopli83** [comment]
Yes, sure I will try this.

**Comment by aravi365** [comment]
@kirtipopli83  any update?

**Comment by NikitaAvraimov-okta** [comment]
Closing this since additional information required for the investigation, feel free to reopen if new details available.
