### ISSUE TITLE
ChromeCustomTab opens outside of the app

### ISSUE THREAD

**Issue by Stickerbox** [okta/okta-oidc-android#225]
Starting from 1.0.15 (I'm testing in 1.0.17), it appears the OktaAuthenticationActivity's launchMode was changed to be singleInstance. This causes a change in behaviour where rather than opening the custom tab inside the app, it now launches a new task outside the app. This has a few issue that we've run into:

1. The user can now go back to the app using the task manager and open another instance of the web auth client before signing in, since it's now opening outside the app's stack
2. Even after successful sign in the CCT lingers as a task in the task manager for some reason
3. The presentation style now is completely different, which has the most jarring affect when logging out.

Is there anything the consumer has to do to avoid these changes? Thanks!

**Comment by JayNewstrom** [comment]
You can avoid this behavior by overriding it in your apps manifest.

Here's an example:
```
        <activity
            android:name="com.okta.oidc.OktaAuthenticationActivity"
            android:launchMode="singleTop"
            tools:replace="android:launchMode" />
```

**Comment by ecexplorer** [comment]
> You can avoid this behavior by overriding it in your apps manifest.
> 
> Here's an example:
> 
> ```
>         <activity
>             android:name="com.okta.oidc.OktaAuthenticationActivity"
>             android:launchMode="singleTop"
>             tools:replace="android:launchMode" />
> ```

This worked for me. Would appreciate this being better documented, including in the React Native SDK documentation.

**Comment by sumanpula** [comment]
This is working great, thank you.
