### ISSUE TITLE
Getting Error when try to Verify or Resend OTP the MFA based on SMS factorType.

### ISSUE THREAD

**Issue by kirtipopli83** [okta/okta-oidc-android#231]
When trying to change the password, in custom sign in android application, always getting Error at the time of verification of the OTP code sent on the registered mobile number as well as while trying to resend the  code on the registered mobile number.

The Error code looks like this when trying to verify : - "{"errorCode":"E0000034","errorSummary":"Forgot password not allowed on specified user.","errorLink":"E0000034","errorId":"oae70KA_nGwSs6cjRPb-NxlPg","errorCauses":[{"errorSummary":"Recovery credential not set."}]}"

The Error when trying to Resend OTP: 
"{"errorCode":"E0000079","errorSummary":"This operation is not allowed in the current authentication state.","errorLink":"E0000079","errorId":"oaecAEKrVMvRAiq93ZGFyj1aQ","errorCauses":[{"errorSummary":"This operation is not allowed in the current authentication state."}]}"

**Comment by NikitaAvraimov-okta** [comment]
Thanks for reaching out @kirtipopli83 Could you please check account recovery rules. To do this you can visit your admin panel and go to Security -> Authentication and check enabled Self-service recovery options and also check if your rules have Change Password and Self-Service Password Reset enabled.

**Comment by JayNewstrom** [comment]
@kirtipopli83 please reopen if you have any more information or questions. Thanks!
