### ISSUE TITLE
WebAuthClient not opening on devices with older OS

### ISSUE THREAD

**Issue by adamshick-Skyward** [okta/okta-oidc-android#237]
I am attempting to run okta 

**Repro step**

1.  Create project that uses WebAuthClient to signin
2. Install on device running Android 7.1.2
3.  Call WebAuthClient#singnIn

**Expected result**
The web client open with the correct login page

**Actual result**
Okta SDK fails silently and the login page does not opened.

**Background**

I am using an unconventional device, DJI Smart controller, which runs a custom version of Android. It initially doesn't have chrome on it but I manually installed it and then tested this and it fails. I ran a more basic version of custom tabs to make sure they work ([https://github.com/ohmae/custom-tabs-sample](https://github.com/ohmae/custom-tabs-sample)) and it works just fine opening a custom tab in chrome

**Comment by adamshick-Skyward** [comment]
That's the weird part. There is no crash no output or anything from after WebAuthClient#singnIn is called. Nothing happens

**Comment by JayNewstrom** [comment]
Ok, doesn't sound like it's going to be an easy fix. I created an internal issue and added it to our backlog. OKTA-394639

**Comment by adamshick-Skyward** [comment]
I was looking through past issues and feature request and saw this one: https://github.com/okta/okta-oidc-android/issues/150

Is there any possibility of adding a webview fall back if custom tabs fails?

**Comment by JayNewstrom** [comment]
@NikitaAvraimov-okta was looking into this, but there were limitations that made this not possible.

I'll let him comment to what those limitations were.

**Comment by adamshick-Skyward** [comment]
Just wanted to check back in to see if @NikitaAvraimov-okta could give me a run down on why webview wouldn't work and if I should go with what this developer did, pulling down the okta sdk and building in webview themselves

**Comment by NikitaAvraimov-okta** [comment]
@adamshick-Skyward we would have some complications with [social login](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) so it`s unfortunately not something we would implement in the nearest future

**Comment by adamshick-Skyward** [comment]
Would it be possible to add a function that does use webview if we don't want to have a social login?

**Comment by EtienneStPierre** [comment]
We are having the same issue, I think this is the same issue that was already fixed here #228 but wasn't released. On my side, I branched the master branch and published it in my maven local, and it worked! @NikitaAvraimov-okta, any idea on the release date for that fix? Thank you!

**Comment by JayNewstrom** [comment]
The fix for https://github.com/okta/okta-oidc-android/issues/228 has been released. Please update to 1.0.19 (note the change in maven coordinates in the release notes: https://github.com/okta/okta-oidc-android/releases/tag/1.0.19

I'm going to close this, but feel free to reopen/comment or open a new issue
