### ISSUE TITLE
This operation is not allowed in the current authentication state

### ISSUE THREAD

**Issue by manasaraok123** [okta/okta-oidc-android#238]
Still not able to solve. Please help. i am getting an error in postman on authentication
"This operation is not allowed in the current authentication state"

**Comment by JayNewstrom** [comment]
Hi thanks for the report. Could you please provide some more information about your issue?

One common thing we like to have people check is that the user they're trying to log in with is assigned to the application in the okta admin dashboard.

**Comment by JayNewstrom** [comment]
I'm going to close this. Please add more information and reopen!
