### ISSUE TITLE
Adding prompt parameter with login value on signIn() doesn't show Sign Out

### ISSUE THREAD

**Issue by akrezic1** [okta/okta-oidc-android#241]
After signing out with one user I want to sign in as another one, but I'm having issues.

One option would be to clear session from browser with calling `WebAuthClient.signOutOfOkta(activity)` but it feels bad as it's launching browser and than leaving it in less than a second, which doesn't look good with all those transitions.

Another option I tried was using payload for signing in as shown below:

```
AuthenticationPayload payload = new AuthenticationPayload.Builder()
        .addParameter("prompt", "login")
        .build();
webClient.signIn(this, payload);
```

But this only opens sign in for current user that needs to enter password only and there is no "Sign out" or "Change user" or whatever. But the funny thing is if you refresh that WebView (using pull to refresh) you will get "Sign out" button.

Before refreshing:
![image](https://user-images.githubusercontent.com/7119798/122355700-66915300-cf52-11eb-960d-fc84b1858e00.png)
After refreshing:
![image](https://user-images.githubusercontent.com/7119798/122355785-79a42300-cf52-11eb-868f-f4ca8554b099.png)

Is there any chance to add that Sign Out on first load? Or is there any other alternative for it?

**Comment by NikitaAvraimov-okta** [comment]
Thanks for reaching out @akrezic1, payload parameter you specified above is used to `prompt the user for authentication, regardless of whether they have an Okta session.` - https://developer.okta.com/docs/reference/api/oidc/#parameter-details
Possible solution is to try out custom sign in flow if you want to avoid using browser at all

**Comment by akrezic1** [comment]
I've taught about that too, but it seems more secure this way as we don't have to handle users password ourselves.

Is there any chance to add "Sign out" to first load of WebView? Shouldn't be a problem as it is there already when you refresh the page, but that's not really user friendly.

**Comment by JayNewstrom** [comment]
Due to the way cookies are handled in chrome custom tabs (the way we launch the browser), we don't have control of logging the user out without launching the web view. If you want to ensure the user is logged out, `WebAuthClient.signOutOfOkta(activity)` is the best option.

**Comment by akrezic1** [comment]
@JayNewstrom That's too bad as it doesn't look really good with all the transitions. Thanks for answering, guess we can close this issue as I'll probably try to find some alternative or hack something out.

**Comment by JayNewstrom** [comment]
Thanks. I'll let our product manager know about the unfortunate user experience (I agree that it's not ideal!), so that our team can prioritize a future enhancement (no promises on timeline for now though).

**Comment by akrezic1** [comment]
Thank you so much, hope it gets fixed! I'll watch out for changes.

**Comment by FeiChen-okta** [comment]
@akrezic1 adding a login_hint along with prompt will log the user out. However your application should provide an input field for the user.

```
           payload = new AuthenticationPayload.Builder()
                    .setLoginHint("user")
                    .addParameter("prompt", "login")
                    .build();
```

**Comment by akrezic1** [comment]
Oh nice, didn't know that. Will try tomorrow, I'm busy now. Thanks!

**Comment by akrezic1** [comment]
@FeiChen-okta Tried it out and it only works if email does not match previously logged in user, so the only way for it to work is if I ask for email from my app and put that hint to Okta WebView which is not really ideal. Guess I'll go with that workaround if our product owner finds it good enough.

**Comment by hansreichenbach-okta** [comment]
@akrezic1 yeah we're aware it's not ideal and are discussing how to improve it internally but can't promise any timelines at this time sadly. Our own Okta Verify is running into the same sub-optimal flow.
