### ISSUE TITLE
Silent failure when bind service failed

### ISSUE THREAD

**Issue by mchemin** [okta/okta-oidc-android#247]
On a Huawei device with chrome installed the okta oidc 1.0.19 failed to bind to the chrome tabs service.

The return of bind service [here](https://github.com/okta/okta-oidc-android/blob/1.0.19/library/src/main/java/com/okta/oidc/OktaAuthenticationActivity.java#L155) is not used and in the case were the service is not launch nothing happened and the user hang there forever and we have no logs nor information about it.

**Comment by NikitaAvraimov-okta** [comment]
@mchemin do you have this issue every time when using Huawei device? Is it reproducable on a sample app?

**Comment by mchemin** [comment]
The issue happens in some conditions on a Huawei Mate 8.
This device does not have Google Chrome installed by default. Then we asked our user to install it, even if he wants to continue using his own default browser.
We discovered this exact scenario which always trigger the failure.
* Launch Chrome and swipe it from the recent task (I assume Huawei is killing the process somehow and does not restart it)
* Launch the example app (Or our own app) (To reproduce the issue, I downloaded the example code from the admin console of Okta - for Android - updated the OIDC SDK version to 1.0.19, the gradle plugin, made some updates to enable the match all flags)
* Start the SSO sign in (Or more globally the web sign in)

### Actual:
The browser is never launched.

### Expected:
* The browser is launched to continue the SSO.
* **OR at least, if it is impossible, could you provide an error code that can be identified so we can prompt a support message to the user.**

## Analysis:
The `bindServiceAndStart` method pointed in the 1st comment can return false if it will surely fail to connect. In this case, the connection callback given to the bindService is never used and we are soft lock waiting for something that will never arrive.
On this Huawei device, Chrome is killed by the system and the system prevent the launch of Chrome services by another app (or automatically) due to battery saving optimisations.
If the user launch Chrome before the test, and keep it in the background, it works properly.
Please note that there's a "Battery menu" in this Huawei device which allows to manage "automatically" this battery optimisation. If the user manually accept that we don't want to optimise the Chrome app, everything seems to work as expected.
