### ISSUE TITLE
After authentication, OKTA browser login tab remains in recent apps.

### ISSUE THREAD

**Issue by gopalp1709** [okta/okta-oidc-android#249]
After authentication, OKTA browser login tab remains in recent apps even if application is closed.
With earlier SDK 1.0.11 browser login tab used to get closed after authentication I mean after successful login.
Now with SDK 1.0.19 it's kept open after login , please suggest if any method or configuration need to add to close login tabs.

**Comment by NikitaAvraimov-okta** [comment]
Thanks for reaching out, we will look for something to fit your requirements

**Comment by JayNewstrom** [comment]
Hi @gopalp1709 does something like what was answered here solve your issue? https://github.com/okta/okta-oidc-android/issues/225

**Comment by gopalp1709** [comment]
After adding the below code as per your suggestion 
<activity
            android:name="com.okta.oidc.OktaAuthenticationActivity"
            android:launchMode="singleTop"
            tools:replace="android:launchMode" />

CCT is getting closed. But I want to navigate to Okta browser login when user logout. 
webAuthClient.signIn(this, payload)

**Comment by JayNewstrom** [comment]
Ok, I'm glad that fixed your initial issue! 

I don't understand your current issue? Could you please describe the desired behavior?

**Comment by gopalp1709** [comment]
Hi it's working as expected after some changes, is there any option to change animation ?
If yes please share the snippet.

**Comment by JayNewstrom** [comment]
You can change the animations for launching the browser with a snippet similar to this:
```java
Okta.WebAuthBuilder builder = new Okta.WebAuthBuilder()
        .withConfig(mOidcConfig)
        .withContext(getApplicationContext())
        .withStartAnimation(..., ...)
        .withExitAnimation(..., ...)
```

Please let me know if you need anything else.

Thanks!

**Comment by gopalp1709** [comment]
Thanks
