### ISSUE TITLE
Stuck in an endless loop using the 

### ISSUE THREAD

**Issue by FabianShallari** [okta/okta-oidc-android#255]
Hey there.

I am stuck in this endless loop while trying the `kotlin-sign-in` sample app with the latest sdk version:

Okta library version: `com.okta.android:okta-oidc-android:1.0.20` 

I have tried to uninstall and reinstall the sample app a couple of times, but nothing works :/ 

Any idea what might be causing this?

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/6090301/126629409-43eb925e-b715-4e6c-838c-c24598ec36f6.gif)

**Comment by JayNewstrom** [comment]
Hi, sorry to hear you're running into issues. I'd be happy to try and reproduce this. Could you give us a little more information about the device you're using? Android version, and chrome version would be helpful. Thanks!

**Comment by FabianShallari** [comment]
Hello. 

Apparently, this was an issue when having both the `kotlin-sign-in` sample and the `web-log-in` sample installed in the device. I tried the login from the `kotlin-sign-in` sample and chose the `web-log-in` to handle the intent result and clicked `always` on the Android system disambiguation dialog since both apps were registered to handle the same intent (and had the same logo).

Thank you very much for your support!
