### ISSUE TITLE
Okta Sign-in page not launching

### ISSUE THREAD

**Issue by syangatkonrad** [okta/okta-oidc-android#258]
Hi, we have had 3 separate incidents of the sign-in page not launching from client's Android phones. 

These are the reported devices:
- SM-G973W (Galaxy S10)
- LM-G820 (LG G8 ThinQ)
- Google Pixel 3A

We unfortunate was not able to reproduce this issue, and was not provided with their Android version or which default browser they have installed.

Just wondering if you have any information or possible leads on this issue, thank you.

**Comment by JayNewstrom** [comment]
Hi, sorry to hear you're running into issues. 

Are you using the latest version of the SDK (right now it's 1.0.20)?

We have heard some similar reports, but it's either come down to something like an Android for work profile blocking access to chrome, or devices that don't have the play store/chrome installed.

If you're able to reproduce this, I'd love to hear about it, and we can work on a fix.

**Comment by syangatkonrad** [comment]
We are using 1.0.17, are there any changes that may affect / fix this going from this version to the latest?

Also just want to confirm the supported browsers are Chrome and Firefox?

**Comment by JayNewstrom** [comment]
There are a few fixes that _may_ fix this issue. But it's hard to know without logs/being able to reproduce the issue.

Chrome and Firefox both support chrome custom tabs, which is what we need for the SDK to work, that being said though, I mostly test with Chrome, so I expect that will work better.

**Comment by gyasistory** [comment]
I am having this same issue but I have been able to resolve it by making the targetSdkVersion 29.  When I change it to 30 or higher and run it on a device running 30 or higher the okta sign-in doesn't open, but it does open on lower versions.

**Comment by JayNewstrom** [comment]
@gyasistory can you recreate this with the latest release of the SDK? `1.0.20`, we've made some fixes for target sdk changes.

**Comment by gyasistory** [comment]
@JayNewstrom Thanks, that was the problem. I was using this from another internal repository.  So I had to upgrade that call to get the latest version of this.  And that fixed my issue thanks for the suggestion.

**Comment by JayNewstrom** [comment]
@syangatkonrad Can I close this issue now? Sounds like updating helped others on this issue.

**Comment by syangatkonrad** [comment]
Yes @JayNewstrom, thank you for your help.
