### ISSUE TITLE
Sample app crashes, couldn't find config

### ISSUE THREAD

**Issue by GeforceA** [okta/okta-oidc-android#261]
Hi,

I download the app and put the my app config values in the res/raw/okta_oidc_config.json file.  they look like this:
  _"client_id": "0oaw8w2glhCDnGa9Z0h7",
  "redirect_uri": "xamarintest.xxxx.login:/callback",
  "end_session_redirect_uri": "xamarintest.xxxx.logout:/callback",
  "scopes": [
    "openid",
    "profile",
    "offline_access"
  ],
  "discovery_uri": "https://loginpreview.xxxx.com"_
when I try to launch the app, it crashes with this info:
_2021-08-13 09:28:03.474 31004-31004/com.okta.oidc.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.okta.oidc.example, PID: 31004
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.okta.oidc.example/com.okta.oidc.example.SampleActivity}: java.lang.IllegalArgumentException: Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain_
it looks like it could not find my config.  
Am I missing some steps before i can run the sample code?
Thanks.

**Comment by GeforceA** [comment]
the discovery_uri is the value from our okta preview account.  I tried to use xxxx.oktapreview.com and had the same result.

**Comment by JayNewstrom** [comment]
Hi @GeforceA if you're looking for a sample app, I'd suggest looking at our [sample apps repo](https://github.com/okta/samples-android/tree/master/browser-sign-in).

When I run this repo, I add these to my `local.properties` file.

```
test.scheme=com.okta.dev-xxx
test.discoveryUri="https://dev-xxx.okta.com/oauth2/default"
test.clientId="xxx"
test.scopes="openid", "profile", "offline_access"
test.endSessionUri="com.okta.dev-xxx:/logoutCallback"
test.redirectUri="com.okta.dev-xxx:/callback"
```

The reason the config file you changed isn't working is due to it being overridden right away. See https://github.com/okta/okta-oidc-android/blob/master/app/src/main/java/com/okta/oidc/example/SampleActivity.java#L403-L415

You could also comment out lines 409-415 to try with the config file approach.

**Comment by GeforceA** [comment]
Thanks for the quick reply again Jay.  I will check out the sample you referring to.  I also did a bit debugging and the exception is actually thrown right before the code part you pointing out.  on line 397, where it trying to use values in BuildConfig.DISCOVERY_URI, which is coming from the default config somewhere and it contains an empty string and that is where the exception is thrown.

**Comment by JayNewstrom** [comment]
Ahh yeah, sorry, I forgot about that. You'll need to use the properties mentioned above in the `local.properties` file in order to run the test app in this repo for now.

**Comment by JayNewstrom** [comment]
@GeforceA is there anything else we can help you with, or can this be closed?
