### ISSUE TITLE
Build fails w/o JCenter/Bintray repository

### ISSUE THREAD

**Issue by ecexplorer** [okta/okta-oidc-android#268]
Currently my app has `jcenter()` as a repository to pull libraries from. If I remove it to prepare for deprecation (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) I get the following build exception:  
```
Could not HEAD 'https://dl.bintray.com/okta/com.okta.android/me/relex/photodraweeview/1.1.3/photodraweeview-1.1.3.pom'. Received status code 403 from server: Forbidden
```

Simply adding `jcenter()` back to the root build.gradle under allprojects > repositories resolves the build issue.

I did notice https://github.com/okta/okta-oidc-android/pull/242 but it appears there is an internal relex/photodraweeview dependency that is still only available in Bintray?

I can confirm that I'm using v1.0.20 via the latest React Native SDK (v2.0.0)

Can the dependency for that view be removed, or otherwise migrated to mavenCentral?

**Comment by JayNewstrom** [comment]
We don't use the photodraweeview mentioned: see https://github.com/okta/okta-oidc-android/blob/master/library/build.gradle#L55-L58

Can you reproduce this in one of our samples?

It's worth noting that 2.0 of our react-native SDK isn't quite ready yet, and we've got a few fixes in flight before it's ready.

**Comment by ecexplorer** [comment]
Not sure why this error would have been caused by another library, but after removing some old bintray code relative to okta, no longer seeing this error.
Good to close.
Thanks for the heads-up on 2.0 RN readiness!
