### ISSUE TITLE
Pocophone F1 does not open browser

### ISSUE THREAD

**Issue by Qwin** [okta/okta-oidc-android#282]
Seems like this issue has been going around the okta forums, but I saw as well that this issue happens on some other phones. Not sure what the cause is but here is some more info about it, I am having the same issue. I do know the code that opens the browser is within this library which is used by the react-native okta library.

https://devforum.okta.com/t/okta-authentication-in-app-browser-within-app-not-working-on-android-pocophone/11547/3

**Comment by JayNewstrom** [comment]
@Qwin  is this related to https://github.com/okta/okta-oidc-android/issues/247

Do you have more information like a stack trace?

**Comment by Qwin** [comment]
@JayNewstrom checking now the issue you provided seeing if its the same

**Comment by FeiChen-okta** [comment]
@Qwin Can you run the following commands to see if a compatible browser is installed:
```
adb shell pm query-activities -a android.intent.action.VIEW -d "https://www.example.com"
adb shell pm query-services -a android.support.customtabs.action.CustomTabsService
```
If the query-services doesn't show any compatible custom tabs service then that device doesn't have a compatible browser.

**Comment by Qwin** [comment]
@FeiChen-okta  will try :)

**Comment by Qwin** [comment]
@FeiChen-okta  ok will try it out

**Comment by FeiChen-okta** [comment]
Match default should work but it doesn't. This is only an issue with browser queries according to googles own samples:

https://github.com/GoogleChrome/android-browser-helper/blob/main/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/TwaProviderPicker.java#L121

We didn't set the default to true cause the documentation says:
https://developer.android.com/reference/android/content/pm/PackageManager#MATCH_ALL
```
This flag should be used with extreme care.
```

**Comment by nasreekar** [comment]
@Qwin @FeiChen-okta  I face the same issue on my Xiaomi Redmi Note 3, and irrespective of adding the below code in the manifest it doesn't work. It works only when I set the flag `browserMatchAll` to true but from the commentary above I understand that it should be used carefully. Not sure how I resolve this issue if that is the case.

` <queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="http" />
    </intent>
</queries>`
