### ISSUE TITLE
SignIn via Web Auth fails in Android Emulator

### ISSUE THREAD

**Issue by BenjYn** [okta/okta-oidc-android#284]
I am having almost identical issues with https://github.com/okta/okta-oidc-android/issues/192.

I'm running this on an Android emulator on both Mac OS X and Windows with no luck so far. 

To quote that issue:

> 
> Background Note: I'm calling this lib via Okta's React Native lib. However, I'm pretty sure the issue is with this lib and not React Native or Okta's Lib for React Native.
> 
> Long story short, calling signIn() which in turn calls webClient.signIn(currentActivity, null) does nothing. I can see the call be made to the discovery endpoint, but nothing happens after that. No errors, no exceptions in logcat, nothing. Not sure if I'm doing something wrong or if something's broken.
> 
> The same operation with the same app works fine when running with an actual device.

**Comment by BenjYn** [comment]
> Can you confirm you have configured `requiredHardwareBackedKeyStore` to `false`?
> 
> If so, could you provide us steps to reproduce? We're not able to reproduce this issue.

I can confirm that `requiredHardwareBackedKeyStore`, using the sample app here: https://github.com/okta/samples-js-react-native/tree/master/browser-sign-in

Here's a recording (apologies for the flickering).

https://user-images.githubusercontent.com/16415858/137967645-78822265-c10c-4215-808e-5429610272f8.mp4

**Comment by JayNewstrom** [comment]
Do you have a stack trace we can look at?
