### ISSUE TITLE
Feature Request: Coroutines Support

### ISSUE THREAD

**Issue by pjkarels** [okta/okta-oidc-android#286]
I get the exception NetworkOnMainThreadException when attempting to call AuthenticationClient.authenticate() when using Kotlin Coroutines. Are there plans to support coroutines?

**Comment by JayNewstrom** [comment]
You may be mistaking SDKs.

https://github.com/okta/okta-auth-java/blob/master/api/src/main/java/com/okta/authn/sdk/client/AuthenticationClient.java

`AuthenticationClient` is part of `okta-auth-java`.

That being said, the calls are meant to happen on a background thread. Are you sure you're switching threads? Could you try something like this?

```
val scope = CoroutineScope(Dispatchers.IO)
scope.launch {
        authenticationClient.authenticate(...)
}
```
