### ISSUE TITLE
Device Code support

### ISSUE THREAD

**Issue by CodyDunlap** [okta/okta-oidc-android#291]
Apologies if this already exists somewhere in the SDK that I'm simply not seeing.

Please add support for authenticating on browserless platforms using the device code grant flow. Currently, I am using the Okta SDK to allow users to authenticate with primary authentication but I'm having to implement the calls for device authentication using OkHttp on my own.

**Comment by JayNewstrom** [comment]
We've already got a few open issues related to this. Please see #280

**Comment by JayNewstrom** [comment]
For anyone interesting in trying out this functionality, we just released the first public beta of a new suite of SDKs here:
- Auth Foundation - https://search.maven.org/artifact/com.okta.kotlin/auth-foundation/0.2.0-BETA/aar
- Web Authentication UI - https://search.maven.org/artifact/com.okta.kotlin/web-authentication-ui/0.2.0-BETA/aar
- OAuth2 - https://search.maven.org/artifact/com.okta.kotlin/oauth2/0.2.0-BETA/aar
- IDX Kotlin - https://search.maven.org/artifact/com.okta.android/okta-idx-kotlin/2.0.0-BETA2/aar

With repos available here:
- https://github.com/okta/okta-mobile-kotlin/releases/tag/0.2.0-BETA
- https://github.com/okta/okta-idx-android/releases/tag/2.0.0-BETA2

The new functionality being focused around DeviceAuthorizationFlow: https://github.com/okta/okta-mobile-kotlin/blob/master/oauth2/src/main/java/com/okta/oauth2/DeviceAuthorizationFlow.kt

We welcome feedback (notes on how to submit feedback in the projects README)

**Comment by CodyDunlap** [comment]
Thanks, @JayNewstrom!
