### ISSUE TITLE
webAuthClient.SignOut was successful but doesn't clear browser session

### ISSUE THREAD

**Issue by satyajitvure91** [okta/okta-oidc-android#292]
I'm trying to signOut of Okta and was able to do that successfully using webAuthClient.SignOut and the onSuccess callback was triggered. But when I try to signIn again the browser returns the previous session. am I missing anything here?
```
    @Provides
    @Singleton
    fun provideWebAuthClient(
        config: OIDCConfig,
        @ApplicationContext context: Context,
        encryptedSharedPreferenceStorage: EncryptedSharedPreferenceStorage
    ): WebAuthClient {
        return OktaClient.WebAuthBuilder()
            .withConfig(config)
            .withContext(context)
            .withStorage(encryptedSharedPreferenceStorage)
            .setRequireHardwareBackedKeyStore(false)
            .browserMatchAll(false)
            .supportedBrowsers("com.android.chrome")
            .create()
    }
```
This is what I'm doing on clicking logout
```
activity?.let { webAuthClient.signOut(it, ALL, object: RequestCallback<Int, AuthorizationException>{
            override fun onSuccess(result: Int) {
                if (result == SUCCESS) {
                    Log.d("LSV", "onSuccess: signed out")
                }
            }

            override fun onError(error: String?, exception: AuthorizationException?) {
                Log.e("Error", exception?.localizedMessage.toString())
            }
        }) }
```
Now when I go back to sign in page and click login, the browser opens and redirects to the app with the previous session.

**Comment by JayNewstrom** [comment]
Please have a look at our sign out documentation. https://github.com/okta/okta-oidc-android#sign-out

You need to use the `signOutOfOkta` method in order to sign the user out from the browser too.

**Comment by JayNewstrom** [comment]
Can you recreate this in our sample applications? We're not seeing this behavior there.

**Comment by satyajitvure91** [comment]
I tried the sample app with our organization's configuration and I still see the same issue. I sign out and clear data and I try to sign in but the same thing happened on the sample app as well.

**Comment by JayNewstrom** [comment]
@satyajitvure91 could you try creating a new dev org and trying with another basic configuration?

**Comment by satyajitvure91** [comment]
I actually did try that with my own sample dev configuration and it is working as intended. Is it something to do with our organization's setup?

**Comment by JayNewstrom** [comment]
Does your `endSessionRedirectUri` match what's in the admin console?
Does your `discoveryUri` match what's in the console?
