### ISSUE TITLE
multiple app not supported 

### ISSUE THREAD

**Issue by yahmi** [okta/okta-oidc-android#295]
@JayNewstrom
Hello teams , 
we have an issue with okta sdk , we try to use for sign in  we had this error message : 
{"type":4,"code":4001,"error":"invalid_redirect_uri","errorDescription":"No uri registered to handle redirect or multiple applications registered"}` 

the config is fine , the main issue is coming from that  we have two apps with the same name and package id , it means we have main app after getting success it launch the second app , do you have any suggestion

**Comment by NikitaAvraimov-okta** [comment]
That is very unlikely, I`ll look what we could do with callback uri`s and custom authorization servers, but it`s best to keep "1 to 1 app to org" relation, you can check our doc on custom authorization servers on how to use tokens obtained from 1 org in another org of yours.

**Comment by JayNewstrom** [comment]
Please consider using multiple redirect urls/schemes, and customizing them as part of your build. This is a feature of the SDK (not a bug!) to prevent phishing.
