### ISSUE TITLE
After Microsoft MFA (multifactor authentication) via call, the custom tab is not getting redirected back to the app

### ISSUE THREAD

**Issue by anandayyanar3450** [okta/okta-oidc-android#298]
Here once I sign in , It navigates the Microsoft login where I enter my credentials and a Microsoft MFA (multifactor authentication) via call is made. After the call the app fails to redirect to the app.
Kindly assist me

**Comment by NikitaAvraimov-okta** [comment]
Can you provide some steps for us to try and reproduce this. Is this something that was working previously? Can it be reproduced in our sample app?

**Comment by JayNewstrom** [comment]
Please reopen with steps to reproduce.
