### ISSUE TITLE
ChromeCustomTab opens outside of the app for first time.

### ISSUE THREAD

**Issue by gopalp1709** [okta/okta-oidc-android#300]
I have observed ChromeCustomTab in recent apps for first time when user try to sign in on new device.
Also I tried on emulator and observed where chrome opens and take consent before sign in page.
After that I removed chrome tab and app from recent. 
Then tried to sign in but it didn't appeared in recent for subsequent sign in. I have already added below code in my app.

`<activity
            android:name="com.okta.oidc.OktaAuthenticationActivity"
            android:launchMode="singleTop"
            tools:replace="android:launchMode" />`

**Comment by NikitaAvraimov-okta** [comment]
Hi @gopalp1709, can you clarify what exactly are you trying to achieve here? Do you want ChromeCustomTab to be asbent in recent apps, right?

**Comment by gopalp1709** [comment]
Yes I want ChromeCustomTab to be absent in recent apps , it's showing CCT and app in recent apps for first time . You can verify on android emulator , ensure emulator is newly created or you can wipe data of emulator and check.

**Comment by NikitaAvraimov-okta** [comment]
Would you please be able to try and reproduce this issue in our sample app?

**Comment by gopalp1709** [comment]
<img width="576" alt="twowindows" src="https://user-images.githubusercontent.com/30046717/152982717-233c2fdf-0e07-4aec-97a1-7570e27c54f5.png">

**Comment by NikitaAvraimov-okta** [comment]
@gopalp1709 it is indeed shown in recent apps if chrome was never launcher prior. We`ll check what we can do to prevent this, thank you for your observation!

**Comment by NikitaAvraimov-okta** [comment]
Internal ref: OKTA-468775

**Comment by JayNewstrom** [comment]
It doesn't look like we can do anything to fix this.

This is happening because Chrome is opening another activity (to ask the user the initial questions). This causes our flow to be overridden.

Due to this being an extreme edge case, I think this is acceptable.
