### ISSUE TITLE
Android Okta login screen not getting translated even adding ui-locales

### ISSUE THREAD

**Issue by Farhin-Shaikh** [okta/okta-oidc-android#302]
### Describe the bug?

In Android we are using below code for changing localization of login screen but text gets translated only for portuguese and english language, It's not supporting for español,francais and may be other languages. Is there any different configuration in Android for this case?

Tried with three options by parsing language code and language into **ui_locales** parameter.
**Option 1 -**
val payload = AuthenticationPayload.Builder()
                .addParameter("ui_locales",Locale.getDefault().language)
                .build()
viewModel.webAuthClient.getWebAuthClient()?.signIn(this, payload)

**Option 2 -**
 val payload = AuthenticationPayload.Builder()
                .addParameter("ui_locales",Locale.getDefault().displayLanguage)
                .build()
viewModel.webAuthClient.getWebAuthClient()?.signIn(this, payload)

**Option 3 -**
val payload = AuthenticationPayload.Builder()
                .addParameter("ui_locales",Locale.getDefault().displayName)
                .build()
            Log.e("Payload language : ", Locale.getDefault().displayName)
            viewModel.webAuthClient.getWebAuthClient()?.signIn(this, payload)

**Following are the values going in payload for respective options -**

Option 1 -
ui_locales -> es   

Option 2 -
ui_locales -> español

Option 3 - 
ui_locales -> español (México)

 

### What is expected to happen?

It should be translated into given ui-locales language.

### What is the actual behavior?

It's only translated into english language.

### Reproduction Steps?

Step 1 - Changing mobile device setting -> Languages and input ->Languages -> Add a language ->Select language to Espanol -> Select region to Mexico.

Step 2 - Opening my app on the same device and its launching okta login page.

Step3 - Page not get translated into Espanol language. Please find attached screenshot.

![okta login screen](https://user-images.githubusercontent.com/99865832/154470853-c6d53e0c-5d06-4da2-a3be-c08e394fed40.png)

Same I have tried for Francias (Canada) getting same result.
 

### SDK Version

1.0.19

**Comment by NikitaAvraimov-okta** [comment]
@Farhin-Shaikh Thanks for reaaching out! We`ll look what we can do, internal ref OKTA-471575

**Comment by Farhin-Shaikh** [comment]
@NikitaAvraimov-okta  Please update, waiting for your response.

**Comment by JayNewstrom** [comment]
@Farhin-Shaikh I'm not able to reproduce. When I update the language on my device, and set Español to the default, it shows up correctly as spanish.

![image](https://user-images.githubusercontent.com/713288/170595050-a14ca27e-0a30-474a-af3f-0579eaee750f.png)

![image](https://user-images.githubusercontent.com/713288/170595131-1c867e57-d01d-4010-8727-2267e4da7cce.png)

**Comment by JayNewstrom** [comment]
Please reopen with steps to reproduce, or reach out to [support](https://support.okta.com/) for more specific information on your specific instance.
