### ISSUE TITLE
Okta web signin is not working on android 11+ devices.

### ISSUE THREAD

**Issue by maheshsompalli** [okta/okta-oidc-android#330]
### Describe the bug?

We are trying to work with android web signin in android 11 devices and it is not opening the web redirect uri.
Below android 10 its working fine.

### What is expected to happen?

It should open web browser in all the devices.

### What is the actual behavior?

Web browser not opening the redirect uri

### Reproduction Steps?

just calling the signin() on button click

### SDK Version

Okta latest

**Comment by JayNewstrom** [comment]
Hi @maheshsompalli this SDK is meant to be used with Chrome.

We recently released https://github.com/okta/okta-mobile-kotlin which intents to replace this SDK, and has much better support for alternative browsers, including ones which don’t support Chrome Custom Tabs.

**Comment by maheshsompalli** [comment]
I will check that, Thank you !
