### ISSUE TITLE
Clear All User Sessions via SDK

### ISSUE THREAD

**Issue by thereallukesimpson** [okta/okta-oidc-android#335]
### Describe the feature request?

Hi. In the docs I can see mention of this functionality in a couple for places, e.g. [here](https://help.okta.com/wf/en-us/Content/Topics/Workflows/connector-reference/okta/actions/clearusersessions.htm) and [here](https://support.okta.com/help/s/question/0D54z00007avlXKCAY/log-out-of-all-devices?language=en_US).

Is there something similar in the Android SDK where we can clear all sessions for a user and force password entry on the subsequent login for all devices on which the user has an active session? Or can you point me to the REST API for this functionality?

### New or Affected Resource(s)

Okta Android OIDC SDK

### Provide a documentation link

https://support.okta.com/help/s/question/0D54z00007avlXKCAY/log-out-of-all-devices?language=en_US
https://help.okta.com/wf/en-us/Content/Topics/Workflows/connector-reference/okta/actions/clearusersessions.htm

**Comment by JayNewstrom** [comment]
Hi @thereallukesimpson I'm not aware of a way to do this from the client side (I think you need a management token to do it)

However, feel free to reach out to support@okta.com, as they will have a better understanding of the entire product ecosystem.
