### ISSUE TITLE
Can i use my own provider?

### ISSUE THREAD

**Issue by poke-fcr** [okta/okta-oidc-android#339]
### Describe the feature request?

Hi, AppAuth library didnt worked for me and i am looking an alternative for it. 

### New or Affected Resource(s)

Okta seems like a popular library. Is it open source and will work with kecloak authentication flow?

**Comment by rajdeepnanua-okta** [comment]
This library is open source, and licensed under Apache License Version 2.0. Here's the [License](https://github.com/okta/okta-oidc-android/blob/master/LICENSE). This library implements OAuth 2.0 and OpenID connect authentication flows. I am not familiar with keycloak authentication flow. If keycloak supports OAuth 2.0, or OpenID connect flows, you could try using  and follow the configuration steps in the readme.

Also, I suggest trying [okta-mobile-kotlin](https://github.com/okta/okta-mobile-kotlin), which is our newer library.
