### ISSUE TITLE
RedirectUri callback is stuck after logging in

### ISSUE THREAD

**Issue by toualee99** [okta/okta-oidc-android#340]
### Describe the bug?

The login is currently working for version 1.0.19. After it was updated to 1.0.20, the login process gets stuck right after logging in. Didn't run into any errors. Not sure if there was anything else that needed to be updated.

I've attached the logcat logs for reference.
[logcat_version_1.0.20.txt](https://github.com/okta/okta-oidc-android/files/9975776/logcat_version_1.0.20.txt)

### What is expected to happen?

Should be able to login after updating the version to 1.0.20.

### What is the actual behavior?

Getting stuck after logging in.

### Reproduction Steps?

Update to version 1.0.19 to 1.0.20.

### SDK Version

1.0.20

### Build Information

buildToolsVersion = '29.0.3'
minSdkVersion = 29
compileSdkVersion = 30
targetSdkVersion = 30
androidXCore="1.6.0"
kotlinVersion = "1.4.10"
gradle version: 6.7.1

android gradle plugin version: 4.2.1

**Comment by rajdeepnanua-okta** [comment]
There aren't many changes between 1.0.19 and 1.0.20, so not sure what could be causing this issue. You should only need to update the sdk version, and nothing else. Could you try newer versions of the SDK and see if you still experience the issue? Any potential fix for this issue would be released into version 1.3.4 or above.

Also, for clarification, what do you mean by the login process getting stuck? Could you also provide more detailed steps to reproduce if possible?

**Comment by toualee99** [comment]
I had the same understanding on updating the version.

The issue seems to be happening after we've made a connection to our okta domain. We've confirmed that a callback is triggered upon making that connection but it is never redirected to our app. The odd thing is that we don't have this issue on version 1.0.19.

I've tried all the other sdk versions of okta. None of them worked except for 1.0.19.

**Comment by toualee99** [comment]
This issue is now resolved. Updating to a newer version of react, react-native, and kotlin fixed the issue. Thanks again for the help.
