### ISSUE TITLE
Native Sign-in questions

### ISSUE THREAD

**Issue by yashrao99** [okta/okta-oidc-android#64]
@FeiChen-okta Thank you so much for pointing me in the way of this SDK, I was going mad with trying to integrate the App-Auth with the Authn SDKs.

I'm almost there, but I'm still receiving this message in the `onError` for the `RequestCallback` following a successful response for the `AuthenticationStateHandlerAdapter` from Okta-Authn-SDK.

```groovy
 D/handleSuccess: expiresAt: 2019-06-19T21:31:48.000Z, status: SUCCESS, relayState: /application/specific, sessionToken: XXX, etc.

i D/NOTAuthorizedOIDC: AuthorizationException: {"type":0,"code":0,"errorDescription":"Invalid status code 401 Unauthorized"} && null
```
I'm still unauthorized. Do I need to send my `client_secret` in the `AuthorizationPayload` or are there any other parameters in the payload? Not sure what I'm missing

For reference, my config file looks as such

```groovy
{
  "client_id": "XXX",
  "redirect_uri": "com.okta.XXX-app:/callback",
  "end_session_redirect_uri": "com.okta.XXX-app:/callback",
  "scopes": [
    "openid",
    "profile",
    "offline_access"
  ],
  "discovery_uri": "https://XXX-api.okta.com/oauth2/default"
}
```

Also, small nit but in the README for the custom sign-in
`new RequestCallback<AuthorizationResult, AuthorizationException>` should just become
`new RequestCallback<Result, AuthorizationException>`

**Comment by FeiChen-okta** [comment]
Hi @yashrao99, Thanks for the error in the readme. 

Client secrets is not supported for our mobile sdk. 

From the response "Invalid status code 401 Unauthorized" it seems your client setup is correct. It could be your server configuration that might be wrong. Can you check your Applications tab assignment in oktapreview.com to see if the person you are signing in with is listed in the Assignments tab?

**Comment by yashrao99** [comment]
Hi @FeiChen-okta, appreciate the quick response.

We are using the same okta apps for both iOS and Android. So it's the same user I've been signing in with in iOS for the last year so I don't believe that's the issue.

However, the okta app used in this flow has the client secret because that's how we authenticate in the iOS app. Would you suggest we create an entirely new okta app for android that doesn't use the client secret flow?

Thanks,
Yashas Rao

**Comment by FeiChen-okta** [comment]
Hi @yashrao99 We don't recommend using client secrets for both iOS and Android because it is not secure. This SDK only supports the option `Client authentication Use PKCE (for public clients)` in Client Credentials section in the General settings tab of your application.

**Comment by yashrao99** [comment]
@FeiChen-okta Gotcha, I will re-write the iOS code and I got this one working as well! Thank you again for all the help
