### ISSUE TITLE
While calling Remote Api getting 401

### ISSUE THREAD

**Issue by swagatdishri** [okta/okta-oidc-android#78]
Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found

I am attaching Authorization: Bearer + Token ,still getiing the error.
Any help will be appreciated.

**Comment by FeiChen-okta** [comment]
Hi @swagatdishri, Can you paste your access token on https://www.jsonwebtoken.io/
and see what the header and payload looks like?

**Comment by swagatdishri** [comment]
Thanks @FeiChen-okta  for the reply here is my header
{
 "typ": "JWT",
 "alg": "RS256",
 "kid": "DjVwG9HA02bDYt5ewWhGHItm-2dcJTWyKd_lu5tY6HA"
}
and payload is 
{
 "ver": 1,
 "jti": "AT.QJYdzq6VrXbfGxZ1pg-xbBh22syKCH28V3jiEu_Hbls.A/JArlo9UydGVvjTy4wYwMa+6Ujssg5G461DjFnhO0M=",
 "iss": "https://dev-*****.okta.com",
 "aud": "https://dev-*****.okta.com",
 "sub": "*****",
 "iat": 1564410409,
 "exp": 1564414009,
 "cid": "*****",
 "uid": "*****",
 "scp": [
  "openid",
  "profile",
  "offline_access"
 ]
}
it is showing **Signing Key    Invalid - Token Signature has failed**
unable to find the cause ,previously when i was using  okta-sdk-appauth-android it was working perfectly.hoping for a right solution

**Comment by FeiChen-okta** [comment]
Hi @swagatdishri the access token might be expired. "iat" and "exp" have a difference of 4 seconds. The okta-sdk-appauth-android APIs call the refresh token endpoint for you if it is expired. This SDK requires the developer to refresh the token themselves. Can you try changing the expiration time longer in your server?

**Comment by swagatdishri** [comment]
Thanks @FeiChen-okta  for giving the clue ,but when i am checking isTokenExpired() returning false it means token is valid but still getting the 401 ,i am thinking the Epoch unix timestamp may be the problem or what?also when calling the api from postman using same access token getting 401.

is there any issues with the new sdk or i am implementing wrongly cant find out,got stock there.

**Comment by FeiChen-okta** [comment]
Setup and features are different but the endpoint access is the same. Check if the server issuer is the same as the one in the jwt
https://dev-*****.okta.com
or
https://dev-*****.okta.com/oauth2/default/

If thats the error you can set the discoveryUri in the SDK to:
"https://dev-*****.okta.com/oauth2/default/.well-known/openid-configuration"
and see if that works.

**Comment by swagatdishri** [comment]
Thanks a ton @FeiChen-okta ,this one worked perfectly.

**Comment by swagatdishri** [comment]
Hi @FeiChen-okta ,while calling refresh token when my access token is not expired  getting the token refreshed,but after the access token is expired  while trying to refresh the token getting "Missing Service Configuration " Exception .

**Comment by FeiChen-okta** [comment]
It is missing the provider configuration. This should be saved your device when you first sign in.
It could be deleted when you changed your discoveryUri. Try uninstalling the app first to clear all the data and try again.
