### ISSUE TITLE
Android Q beta: Can't start OktaAuthenticationActivity

### ISSUE THREAD

**Issue by janvde** [okta/okta-oidc-android#83]
I'm on the Android Q beta 6 and it seems that the OktaAuthenticationActivity can't be started due to the restrictions on opening activities from background in Android Q (see https://developer.android.com/preview/privacy/background-activity-starts).

When running 

`client.signIn(this, null);` 

the following can be seen in logcat:

 `I/ActivityTaskManager: START u0 {flg=0x24000000 cmp={packagename redacted}/com.okta.oidc.OktaAuthenticationActivity (has extras)} from uid 10383` 

but the expected custom tab doesn't appear.

**Comment by FeiChen-okta** [comment]
Hi @janvde, Did you test on the emulator or a real device? I've been testing on the emulator and it is working.

Based on the the following list of allowed background starts:
https://developer.android.com/preview/privacy/background-activity-starts

OktaAuthenticationActivity meets more than one of those requirements so the issue doesn't look like a background activity restrictions problem. Do you see the following in the logs?

```bash
Background activity start [callingPackage: package-name, ...]
```

**Comment by janvde** [comment]
I'm running it on a Google Pixel 3. I don't see the `Background activity start .. `in the logs. If I run the same code on an emulator (Pixel 3 API 27) it works as expected.

**Comment by FeiChen-okta** [comment]
Thanks for the info. I'll get a real device and see if I can reproduce the issue.

**Comment by FeiChen-okta** [comment]
Hi @janvde. I've tried on a real device and can't reproduce the issue. Did you try using the sample application? One thing to note is that the sdk doesn't allow multiple apps with the same redirect scheme. When trying the sample you should uninstall the previous one, if it is reusing the same redirect scheme.

**Comment by FeiChen-okta** [comment]
Can't reproduce issue on Android 10 release.

**Comment by TuiKiken** [comment]
@FeiChen-okta  I have the same problem. Android 8 and higher works well, but on Android 7 after calling `signIn` method, my interface freezes and status bar changes color to black. It seems that the pop-up window with the authorization form overlaps my interface, but does not display anything.

My logs looks like:
![Screen Shot 2020-07-06 at 16 24 55](https://user-images.githubusercontent.com/959821/86600135-5209b400-bfa8-11ea-9684-796bf6fa3d3a.png)

**Comment by FeiChen-okta** [comment]
Hi @TuiKiken I don't think the issue is related to this one. Can you open new issue with the logs? When you call sign-in the sdk is trying to open chrome or the compatible browser on your device. Are you testing on a real device or Android 7 emulator?
