### ISSUE TITLE
WebAuthClient callback doesn't show result

### ISSUE THREAD

**Issue by janvde** [okta/okta-oidc-android#84]
I'm trying to handle the callback from the chrome custom tab. I have a WebAuthClient to which I pass the result of the redirect.

```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        Timber.d("onActivityResult: $data")
        //must pass the results back to the WebAuthClient.
        webClient.handleActivityResult(requestCode, resultCode, data)
 }
```

After logging in I can see the onActivityResult being called in the logs:

`onActivityResult: Intent { act=com.okta.oidc.OktaRedirectActivity.REDIRECT_ACTION dat={packagename redacted}:/callback?code={code redacted} &state={state redacted} flg=0x24000000 cmp={packagename redacted}/com.okta.oidc.OktaAuthenticationActivity }`

However, the callback that's registered to the WebAuthClient doesn't do anything:

```
webClient.registerCallback(object : ResultCallback<AuthorizationStatus, AuthorizationException> {
            override fun onSuccess(status: AuthorizationStatus) {
                println("DEBUG: $status")
            }

            override fun onCancel() {
                println("DEBUG: cancel")
                //authorization canceled
            }

            override fun onError(msg: String?, exception: AuthorizationException?) {
                println("DEBUG: $exception")
            }

        }, this)
```

I do notice in the logs that there's an issue with handler:

```
2019-08-14 17:04:09.340 29528-29544/? W/MessageQueue: Handler (android.os.Handler) {405fca8} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {405fca8} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
        at android.os.Handler.enqueueMessage(Handler.java:662)
        at android.os.Handler.sendMessageAtTime(Handler.java:631)
        at android.os.Handler.sendMessageDelayed(Handler.java:601)
        at android.os.Handler.post(Handler.java:357)
        at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
        at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
        at android.os.Binder.execTransact(Binder.java:697)
```

**Comment by FeiChen-okta** [comment]
Hi @janvde , The call backs are posted using the main looper by default so it's to the main thread unless you set your own executor. Where are you initializing `WebAuthClient`? Are you using any dependency injection like dagger?

**Comment by FeiChen-okta** [comment]
@janvde I think I've reproduced the issue. If your activity extends FragmentActivity or any of its derived classes you don't need to override

```kotlin
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        Timber.d("onActivityResult: $data")
        //must pass the results back to the WebAuthClient.
        webClient.handleActivityResult(requestCode, resultCode, data)
 }
```

But if you did override `onActivityResult` you should call 
```kotlin
super.onActivityResult(requestCode, resultCode, data)
```

See the following for a more details:
https://github.com/okta/okta-oidc-android#onactivityresult-override

**Comment by janvde** [comment]
@FeiChen-okta Thanks, that helped me resolve the issue.
