### ISSUE TITLE
How to change password and update user profile

### ISSUE THREAD

**Issue by swagatdishri** [okta/okta-oidc-android#86]
hi @FeiChen-okta  how can i change password and update user profile,unable to find which method to call

**Comment by FeiChen-okta** [comment]
That functionality is not part of the OpenID Connect specification. Chrome custom tabs should handle all these cases. But if you want to implement these functionality in-app you will have to implement your own REST api calls to:
https://developer.okta.com/docs/reference/api/authn/
https://developer.okta.com/docs/reference/api/users/

**Comment by dapp** [comment]
Is this still the case?  There's no okta hosted change password screen?
