### ISSUE TITLE
signOutFromOkta() can fail silently

### ISSUE THREAD

**Issue by davidhartley** [okta/okta-oidc-android#94]
It seems that in some cases, if the tokens have already been cleared for example, signOutFromOkta() will fail without hitting any of the callbacks. No success, failure, or cancel.

I'd like to move the user to the logged out screen of our app only once sign out is attempted but if there is a case where it could fail silently, this could break that logic. I've added a check to make see if sessionClient.isAuthenticated() returns true before signOutFromOkta() is called but I'm still concerned there could be a case where this returns false but the user still needs the browser to be signed out.

Is this because a token is required to sign the user out of their browser? I would still expect a failure callback in this case.

**Comment by FeiChen-okta** [comment]
@davidhartley Yes a idToken is needed for sign out. If the tokens have been cleared then it won't be possible to signOutFromOkta. I suspect that it won't even attempt to perform the action so it fails silently which is not the best behavior. I'll add a return to make the failure detectable.

**Comment by FeiChen-okta** [comment]
Fixed in 1.0.4
